### ISSUE TITLE
Support 'txReportQueue' feature from Datomic  

### ISSUE THREAD

**Issue by nickik** [replikativ/datahike#103]
In order to make a simple event-based system having the ability to subscribe to changes would be useful.

**Comment by whilo** [comment]
We would probably provide a core.async interface for that. It should not be too hard to wrap the transact function to provide a similar functionality already.

**Comment by whilo** [comment]
@nickik Would `core.async` work for you or have you found another solution?

**Comment by mrapogee** [comment]
Doesn't `listen!` provide this functionality already?

**Comment by whilo** [comment]
Yes, it does. We just do not expose it officially and it could change once we have a connection to a remote transactor.

**Comment by theronic** [comment]
DataScript already has d/listen! and I use it frequently. This is a +1 for needing d/listen! in Datahike, please.

**Comment by kordano** [comment]
We moved `listen` to the `api` namespace. You may use it from there: https://cljdoc.org/d/io.replikativ/datahike/0.3.3/api/datahike.api#listen
