### ISSUE TITLE
Support for tuples

### ISSUE THREAD

**Issue by den1k** [replikativ/datahike#104]
Tuples recently landed ind atomic on-prem and cloud. Personally, that was always a missing piece of datomic and I'd love for it to land in datahike.

https://docs.datomic.com/on-prem/schema.html#tuples

**Comment by kordano** [comment]
I'll add it with datahike `0.2.2`

**Comment by jjtolton** [comment]
@kordano discussed this briefly in the clojurians slack channel.  Want to make sure you're in alignment with the proposed behavior changes: https://github.com/tonsky/datascript/issues/323#issuecomment-582485607

The schema would, of course, be Datahike/Dataomic compatible per https://docs.datomic.com/on-prem/schema.html#composite-tuples.  

I'm still uncertain about the behavior of pulls/queries in relation to tuples, so want to confirm that with you.

**Comment by den1k** [comment]
Thanks for considering my input. I want to be upfront in saying I haven't yet used tuples in datomic so I don't have good intuition for the design decisions waiting to be made here. Is there reason to deviate (far) from datomic?

**Comment by jjtolton** [comment]
Gonna try to match it as closely as possible!  @kordano I just want to verify that I'm not doing a parallel effort if you've already picked this up and started working it?

**Comment by kordano** [comment]
Hi @jjtolton I'm currently not working on that. Thanks for your help.

**Comment by theronic** [comment]
Excited for tuple support!

**Comment by jjtolton** [comment]
Man I'll tell you what I've entirely fallen off the horse on this one, my
bad.  I've tried and failed several times over the months to add tuples to
datascript but the code is quite intricate and I haven't had enough
dedicated time to do it.  The team has told me that it might be easier in
Datahike so perhaps I should start here first -- but if anyone has more
dedicated time and would like to pick this up please do so because
unfortunately I am slammed these days.

**Comment by theronic** [comment]
@jjtolton can you elaborate on some of the challenges / dead ends? I imagine one of the hardest parts is query optimization for unifying against tuples.

**Comment by jjtolton** [comment]
Here's a cross reference to where I'm working on it for datascript:
https://github.com/tonsky/datascript/issues/323
The challenge comes from the fact that I don't have an adequate mental
model for how datascript works under the hood and I haven't had enough time
to study it.  The code is very intricate, and the solution requires
finesse.  It *seems* like if you have a proper mental model for how the
moving parts work together, the actual change would be 20-50 LOC --
possibly less.  Not a significant overhaul.  But you would need to be
deeply familiar with the underlying mechanics.

**Comment by kordano** [comment]
Integrated with the release `0.3.3`.
