### ISSUE TITLE
Updating raw vector and map values fails

### ISSUE THREAD

**Issue by pm4r** [replikativ/datahike#11]
I have schema with two items with :cardinality/one. In :my/vec I'm going to store vector and in :my/map a hash-map (not a good design obviously but it's useful for quick prototyping). First transaction which adds new data works as expected, however another one which is supposed to change stored values fails.

Splitting them into separate transaction shows that updating vector actually adds another value to db (like schema is being ignored), and updating map silently fails. It works just the same for db without schema (:my/vec is appended, :my/map fails).

I've tested same code with datascript and it works as expected - both values were changed.
See example below:
```clojure
(def schema {:my/id {:db/cardinality :db.cardinality/one
                     :db/unique :db.unique/identity}
             :my/vec {:db/cardinality :db.cardinality/one}
             :my/map {:db/cardinality :db.cardinality/one}})
(def uri "datahike:mem:///dbtest")
(d/create-database-with-schema uri schema)
(def conn (d/connect uri))

@(d/transact conn [{:my/id "x"
                    :my/vec ["a" "b" "c"]
                    :my/map {:a "a" :b "b" :c "c"}}])
(d/seek-datoms @conn :eavt) ; all fine, three datoms there

@(d/transact conn [[:db/add [:my/id "x"] :my/vec ["x" "y" "z"]]
                   [:db/add [:my/id "x"] :my/map {:x "x" :y "y" :z "z"}]])
(d/seek-datoms @conn :eavt) ; problem: nothing changed in db, also no exception or warning

;let's try it separately
@(d/transact conn [[:db/add [:my/id "x"] :my/vec ["x" "y" "z"]]])
(d/seek-datoms @conn :eavt) ; problem: new value was added instead of replaced old one
(d/pull @conn '[*] [:my/id "x"]) ; returns old value for :my/vec
(d/q '[:find ?e ?v
       :where [?e :my/vec ?v]]
  @conn) ; shows both value for same entity

@(d/transact conn [[:db/add [:my/id "x"] :my/map {:x "x" :y "y" :z "z"}]])
(d/seek-datoms @conn :eavt) ; problem: value was not added
```

**Comment by kordano** [comment]
Thanks, I'll have a look at it.

**Comment by whilo** [comment]
You are peeking into the internals, which is ok, but you have to use `:eavt-durable`, we still have to change that to `:eavt` with the next cleanup (probably rebase on upstream datascript). This should also address the pull issue. The actual bug you are describing is visible in 
~~~clojure
(d/q '[:find ?e ?v
       :where [?e :my/vec ?v]]
  @conn)
~~~
My suspicion is that something is wrong with schema handling the memory backend.

**Comment by grischoun** [comment]
I started having look at the problem.
When I try the failing transaction:

**Comment by pm4r** [comment]
@grischoun Actually I do have same stack trace at this transaction. I didn't realize it earlier because It turns out if I evaluated expressions one by one in my editor (Atom + ProtoRepl) it didn't evaluate derefing future so I didn't see exception, but executing larger block at once indeed throws it. That explains why db had nothing related to that transaction.

@whilo I didn't know about :eavt-durable, will remember that in future. I used :eavt almost exclusively to check what's inside when I see something unexpected,

**Comment by whilo** [comment]
We will get rid of the `:eavt-durable` and `:eavt` distinction. Right now we are framing datahike as a joint database for ClojureScript and Clojure and will probably rebase it on a current version of datascript to make it cleaner. This should be transparent to users through the import/export upgrade procedure.

**Comment by whilo** [comment]
Uh that went quick at closing the issue, I will reopen it for now until we have the fixed hitchhiker tree tested with datahike.

**Comment by whilo** [comment]
This fixes the issue, I have tested it.

**Comment by whilo** [comment]
There are still the schema problems open though. I think datahike should throw if you try to assign the same attribute multiple times, which it doesn't here.
