### ISSUE TITLE
Provide out-of-the-box support for redis backend

### ISSUE THREAD

**Issue by jjtolton** [replikativ/datahike#119]
Support the following:

```clojure 
(d/create-database "datahike:redis://redis-server:snort@localhost:6379/")
```

and should work as expected.

**Comment by kordano** [comment]
Thanks @jjtolton , I'll get to it in the next days.

**Comment by kordano** [comment]
I'll add it to the 0.2.2 release and mention you in the change log if that is alright.

**Comment by jjtolton** [comment]
@kordano no problem, thank you!.  It might be a good idea to close https://github.com/replikativ/konserve-carmine/pull/3 first and then update the `konserve-carmine` dep to `"0.1.3"` so that we can add the most polish to 0.2.2!

**Comment by whilo** [comment]
Hey @jjtolton! I have merged your changes into `konserve-carmine` and pushed `0.1.3` to clojars. What are the next steps to populate the `datahike-redis` repository?

**Comment by jjtolton** [comment]
It should be a fairly straightforward fairly, I’ve just been buried work.
 :O I should have time this weekend.

**Comment by jjtolton** [comment]
@whilo https://github.com/replikativ/datahike-redis
Populated :)
Needs to be pushed to your clojars then I can update instructions.  Also need to setup travis or circle-ci to do tests and integration tests with redis.

**Comment by whilo** [comment]
Thanks a lot! I have pushed `0.1.0-SNAPSHOT` onto clojars. Having travis or circle-ci set up would be really good! :)

**Comment by jjtolton** [comment]
Great :) I'll update the README today

**Comment by whilo** [comment]
@jjtolton It would be interesting for us to know how your experience with Redis is so far. We have a benchmark suite now and will also include the redis backend in there. Let me know if we can help to setup CI.

**Comment by jjtolton** [comment]
Hi there!  Sorry for late reply.  There performance seems like it's O(n log
n).  It seems as if that the entire DB gets loaded into memory from redis
on each transaction and then is rewritten to redis on each transaction.  At
first the performance is ok but when I hit it with a huge amount of data
the lag starts to become noticeable over time.  I think that there would
probably have to be a rewrite of the underlying abstraction mechanism.  I
wish that I had time to do it but work has really been keeping me busy :(
