### ISSUE TITLE
lein repl crashes with OpenJDK 10 on Ubuntu 18.04

### ISSUE THREAD

**Issue by kordano** [replikativ/datahike#12]
Process crashes with `java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(cljs/closure.clj:1:1)` with
```
java --version
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3, mixed mode)
```

**Comment by kordano** [comment]
Possible fix via latest ClojureScript version, but needs to be tested.

**Comment by TimoKramer** [comment]
how to test this? I used Ubuntu 18.04 with JDK11 and there was no problem.

**Comment by kordano** [comment]
With the latest version this doesn't occur any more.
