### ISSUE TITLE
:db/noHistory support

### ISSUE THREAD

**Issue by den1k** [replikativ/datahike#129]
Transacting:
```
(def schema
  [{:db/ident       :foo/bar
    :db/cardinality :db.cardinality/many
    :db/valueType   :db.type/ref
    :db/noHistory   true}])
```

fails. Can noHistory be supported by datahike?

**Comment by kordano** [comment]
As I understand it, you want only support the history for specific attributes. This should be possible.

**Comment by den1k** [comment]
Yes, equivalent to datomic: https://docs.datomic.com/on-prem/schema.html#nohistory

**Comment by kordano** [comment]
OK, I've added it in #136 and it will be available with the next release.

**Comment by den1k** [comment]
Thanks so so much @kordano! So glad to have an open source datomic :)
