### ISSUE TITLE
Schema Migration

### ISSUE THREAD

**Issue by mgerlach-klick** [replikativ/datahike#13]
I saw in #4 that schema migration is not currently supported. Are there plans to support this in the future? What's the current workaround for schema migration? Load the database with the old schema, dump it to a file, delete the database, create a database with the new schema and import the data dump?

**Comment by whilo** [comment]
Yes, this is unfortunately true. You can also overwrite the schema in the database yourself, if you know that it is consistent with its current value. 

~~~clojure
(swap! conn assoc :schema new-schema)
(datahike.api/transact! conn [])
~~~

should do the trick.

**Comment by mgerlach-klick** [comment]
Oh, good to know! Thank you @whilo !

**Comment by mgerlach-klick** [comment]
I don't think this actually works.

I modified a schema to make one attribute `:db/isComponent true` and `swap!`ed it in. This had no effect on the queries. I'm guessing I would have to modify `:(schema conn)` in some way as well?

**Comment by whilo** [comment]
@mgerlach-klick Yes, that is true. Did it work for you? I haven't found the time yet to figure it out, but we will aim to fix this over the next months with full schema support.

**Comment by mgerlach-klick** [comment]
I don't recall. I believe I gave up before I got to that point. Maybe ping me once this is working and I'll give datahike another try?

**Comment by px0** [comment]
I'm excited about trying v0.2. Is schema migration working now?

**Comment by px0** [comment]
Replying to myself, found this: https://github.com/replikativ/datahike/blob/master/doc/schema.md#migration

**Comment by tatut** [comment]
Adding new attributes to any `:db/ident` entities seem to fail

```clojure
(defn dh-update-exception []
  (let [uri "datahike:mem://test"]
    (datahike.api/create-database uri)
    (let [c (datahike.api/connect uri)]
      ;; Add two enum values
      (datahike.api/transact c {:tx-data [{:db/ident :task.status/in-progress}
                                          {:db/ident :task.status/complete}]})

      ;; Later we realize we want to trac which enum values belong together
      (datahike.api/transact c {:tx-data [{:db/ident :enum/attribute
                                           :db/valueType :db.type/keyword
                                           :db/cardinality :db.cardinality/one}]})

      ;; Then we update existing enum values
      (datahike.api/transact c {:tx-data [{:db/ident :task.status/in-progress
                                           :enum/attribute :task/status}
                                          {:db/ident :task.status/complete
                                           :enum/attribute :task/status}]}))))
```

Running that will throw:
```Update not supported for these schema attributes
   {:error :transact/schema,
    :entity
    {:db/ident :task.status/in-progress, :enum/attribute :task/status},
    :invalid-updates #:enum{:attribute [nil :task/status]}}```
