### ISSUE TITLE
transact throws on dates

### ISSUE THREAD

**Issue by den1k** [replikativ/datahike#131]
```
(def conn (d/connect <uri>))

(def schema
  [{:db/ident       :name
    :db/valueType   :db.type/keyword
    :db/unique      :db.unique/identity
    :db/cardinality :db.cardinality/one}
   {:db/ident       :added
    :db/valueType   :db.type/instant
    :db/cardinality :db.cardinality/one}])

(d/transact conn schema)
(d/transact conn [{:name :foo :added (java.util.Date.)}]) ; fine but...
(d/transact conn [{:name :foo :added (java.util.Date.)}]) ;; throws

Execution error (ExceptionInfo) at hitchhiker.tree.key-compare/throw-unsupported-type (key_compare.cljc:15).
Type not supported:class java.util.Date
```

**Comment by den1k** [comment]
It looks like a `Date` comparator is missing in hitchhiker-tree.

https://github.com/replikativ/hitchhiker-tree/blob/master/src/hitchhiker/tree/key_compare.cljc#L158

**Comment by whilo** [comment]
That is unfortunately correct. Thank you for reporting this issue!

**Comment by whilo** [comment]
This should fix the issue: https://github.com/replikativ/hitchhiker-tree/commit/ed1df495f0889dfc87cfa59f038272f3b9fa7807#diff-7fcef62d93fdd97c3e94c180c85420efR174. You can manually inject the hitchhiker-tree `0.1.7` and confirm that it works, if you like. This will be part of our pending `0.3.0` release. We might want to support more date types, e.g. the ones documented here that do not require external dependencies https://lambdaisland.com/blog/2017-07-26-dates-in-clojure-making-sense-of-the-mess.

**Comment by whilo** [comment]
I will close this issue, @den1k  feel free to open further issues.
