### ISSUE TITLE
Postgres connections requiring SSL not supported

### ISSUE THREAD

**Issue by kommen** [replikativ/datahike#133]
When a postgres connection url specifies options such as `:ssl true`, they are not passed on to jdbc driver. See https://github.com/clojure/java.jdbc#example-usage which specifies `:ssl` and `:sslfactory`.

This is critical if one wants to use a hosted Postgres Database like from [heroku](https://www.heroku.com/postgres), which requires ssl for connecting.

**Comment by whilo** [comment]
This requires fixing here: https://github.com/replikativ/datahike-postgres/blob/master/src/datahike_postgres/core.clj. @kordano @TimoKramer I think this is addressed by the new configuration approach, right?

**Comment by whilo** [comment]
Nonetheless, it should be easy to patch the current version of `datahike-postgres` to support this to get you started.

**Comment by TimoKramer** [comment]
it is not directly addressed by #128 but good to know what it needs to fulfil in the future. I could add this option after the PR is merged.

**Comment by kommen** [comment]
I was able to get it working with a custom `datahike-postgres.core/pg-path`. To also make it work with the configuration as a string, a diffenrent implementation of `to-jdbc-uri` is needed as well, as the currently used one does not support query strings in the uri (it silently ignores them):

https://github.com/pupeno/to-jdbc-uri

**Comment by whilo** [comment]
Thanks for just getting it done in the mean time. I did not know about `to-jdbc-uri`.

**Comment by TimoKramer** [comment]
needs to be released together with datahike-postgres:
https://github.com/replikativ/datahike-postgres/pull/6

**Comment by TimoKramer** [comment]
BTW https://gist.github.com/mrw34/c97bb03ea1054afb551886ffc8b63c3b is quite useful to test it locally
