### ISSUE TITLE
as-of is unreliable for dates since transactions might have the same exact dates

### ISSUE THREAD

**Issue by vlaaad** [replikativ/datahike#148]
### Context

Since Datahike [does not support tx ids as time points](https://github.com/replikativ/datahike/issues/147) for `as-of`, one needs to use dates to get db at a particular transaction time point.

### Problem

Different transactions might have the same exact insts, which makes the earlier transaction "shadow" the latter when using `as-of` with latter transaction's inst.

### Repro
```clj
(let [uri "datahike:mem://as-of-tx-insts-repro"
      _ (d/create-database uri :initial-tx [{:db/ident :user/name
                                             :db/valueType :db.type/string
                                             :db/cardinality :db.cardinality/one}])
      conn (d/connect uri)
      alice-tx (:db/current-tx (:tempids (d/transact conn [{:user/name "Alice"}])))
      bob-tx (:db/current-tx (:tempids (d/transact conn [{:user/name "Bob"}])))
      db (d/db conn)
      alice-inst (:db/txInstant (d/pull db '[*] alice-tx))
      bob-inst (:db/txInstant (d/pull db '[*] bob-tx))]
  [alice-inst
   bob-inst
   (d/datoms (d/as-of db bob-inst) :eavt)])
```
You should evaluate this code several times to catch the time when both insts are equal. In that case, returned db will be as-of Alice transaction and will contain only 4 datoms (as opposed to case when alice and bob insts are not equal that has 6 datoms). 

### Expected result

I want to be able to reliably get a database at a time point of a particular transaction's instant.

### Actual result

For my intention to get a database at a time point of some particular transaction I might receive a database for a time point of a different transaction if these transactions happened to be committed within the same millisecond.

I would prefer if the solution to this problem was making Datahike's `as-of` accept transaction IDs, but enforcing different insts for different transactions is also fine.

**Comment by kordano** [comment]
Fixed with #202
