### ISSUE TITLE
Support for uniqueness using db.type/instant

### ISSUE THREAD

**Issue by Heliosmaster** [replikativ/datahike#155]
In my schema i have something like
```
{:db/ident       :something/time
 :db/valueType   :db.type/instant
 :db/unique      :db.unique/identity
 :db/cardinality :db.cardinality/one}
```
When I try to add more dates which already exist, I get: 

```
Execution error (ExceptionInfo) at hitchhiker.tree.key-compare/throw-unsupported-type (key_compare.cljc:15).
Type not supported:class java.util.Date
```

I know it's not a problem in datahike per se, but in a lib you build upon, but it still means that dates do not fully work when using datahike.

**Comment by whilo** [comment]
This is fixed in ´[io.replikativ/hitchhiker-tree "0.1.7"]´ and already part of our pending release. See also #131. Sorry for the inconvenience.

**Comment by Heliosmaster** [comment]
Ah, great to know. May i suggest adding the upcoming stuff to an 'unreleased' entry in the changelog? :)

**Comment by whilo** [comment]
Yes, we also need monthly bugfix releases. This is our second major release as a team and pulling everything together has proven to take too long. Please excuse your time wasted on this. The release should be out this week @kordano.
