### ISSUE TITLE
create general datahike SQL jdbc backend

### ISSUE THREAD

**Issue by kordano** [replikativ/datahike#161]
Instead of using separate backends for sql backends Datahike should have one sql backend which maps directly to the jdbc drivers. 

- [x] extend and move datahike-pg to datahike-jdbc
- [x] extend and move konserve-pg to konserve-jdbc
- [ ] describe datahike-jdbc as the successor in the docs

**Comment by whilo** [comment]
A version of this by @alekcz is available here: https://github.com/alekcz/konserve-jdbc

**Comment by TimoKramer** [comment]
current jdbc spec https://download.oracle.com/otn-pub/jcp/jdbc-4_3-mrel3-eval-spec/jdbc4.3-fr-spec.pdf?AuthParam=1591192807_8aebdb4779b50c0bbed0cf7f725d8964

**Comment by TimoKramer** [comment]
![grafik](https://user-images.githubusercontent.com/4785848/83646172-970a8700-a5b3-11ea-9f6f-0fb71b1f4d1a.png)

**Comment by TimoKramer** [comment]
should we close this issue? It might take some time until datahike-jdbc is ready to replace datahike-postgres

**Comment by alekcz** [comment]
@TimoKramer I can get it there over the weekend. Do you have an idea of what's still missing for it to replace datahike-postgres?

**Comment by TimoKramer** [comment]
Hi @alekcz and thanks! I think the main problem is that datahike-jdbc brings the konserve 0.6.0 with it and when you are using datahike it loads konserve 0.5.1 and then datahike-jdbc does not work. so this is basically a question of when we can use datahike with konserve 0.6.0 I guess. Or making konserve-jdbc work with 0.5.1?!

**Comment by whilo** [comment]
It should actually already work, because we have not changed the konserve protocols to the outside, so it might be just a dependency issue (?).

**Comment by TimoKramer** [comment]
I think it might work but the question is if you want datahike to use the konserve snapshot?!

**Comment by whilo** [comment]
No, you cannot use SNAPSHOT dependencies in releases on clojars in fact. But we can do a SNAPSHOT release of Datahike itself with the SNAPSHOT dependency and then release them together once everything fits. I think this is what @kordano asked for.

**Comment by TimoKramer** [comment]
waiting for https://github.com/replikativ/konserve/issues/31

**Comment by whilo** [comment]
@TimoKramer You mean you wait for the konserve version, not the garbage collector, right?

**Comment by TimoKramer** [comment]
@whilo exactly. I thought this is more or less the same.

**Comment by TimoKramer** [comment]
After the PR https://github.com/replikativ/datahike-jdbc/pull/12 is merged. I will change the documentation of using SQL backends in the docs and mark datahike-postgres as superseded.
