### ISSUE TITLE
PostgreSQL backend throws error on configuring with map.

### ISSUE THREAD

**Issue by theronic** [replikativ/datahike#164]
Please consider letting me pass in configuration as arguments via `(d/create-database config)` instead of relying on Environ, which is [exploding for me](https://github.com/weavejester/environ/issues/91) at require time, forcing me to kill the REPL to retry. Also hurts testability.

**Comment by TimoKramer** [comment]
@theronic Does this still need assistance or did you get enough help by weavejester?

**Comment by theronic** [comment]
Can close. The issue with environ was that `.lein-env` had some empty lines in it (it's not supposed to be hand-edited), which caused environ to crash at require-time, and can't be re-imported until restarting REPL, which blocked me from using datahike for a little while. I would still lean toward explicit configuration with defaults in-code.

**Comment by theronic** [comment]
Just got bit by this again when I tried to deploy my app using Dokku. I don't have a `.lein-env` in source and I don't use deps.edn and not Leiningen, so environ crashes my app at runtime even though all my environment variables are set:

```
2020-05-27T16:19:39.385292508Z app[backend.1]: Picked up JAVA_TOOL_OPTIONS: -Xmx300m -Xss512k -XX:CICompilerCount=2 -Dfile.encoding=UTF-8
2020-05-27T16:19:54.427426555Z app[backend.1]: Syntax error (IllegalArgumentException) compiling at (environ/core.clj:39:1).
2020-05-27T16:19:54.427466504Z app[backend.1]: Don't know how to create ISeq from: clojure.lang.Symbol
```

Solution is to add an empty `.lein-env` file to repo.

**Comment by TimoKramer** [comment]
Could you please elaborate a bit. You are writing that you "don't use deps.edn and not Leiningen". What do you use then? Which environment-variables did you set? It would be good if you provided content for the variables as far as possible so that we can reconstruct  the issue.
Thanks

**Comment by theronic** [comment]
@TimoKramer edit: sorry typo. Meant I *do* use deps.edn and Clojure CLI tools.

**Comment by TimoKramer** [comment]
I am closing this issue because I don't know how to reconstruct the error and if environ would not support deps.edn that would mean this issue needed to be there and we had to reevaluate the dependency.

**Comment by TimoKramer** [comment]
So it seems that there is an issue with configuring PostgreSQL backend with the new way of configuring. That is what I  experienced working on https://github.com/replikativ/datahike/issues/167.
renaming the issue.

**Comment by TimoKramer** [comment]
it works with configuration passed explicitly. it only fails when using properties or env-vars.

**Comment by theronic** [comment]
@TimoKramer that error looks like a missing SQL driver, unrelated to the method of configuration.

Btw. `.lein-env` is supposed to be a nested EDN map, not newline-separated KEY=VALUE assignments.

**Comment by TimoKramer** [comment]
added an integration-test to use environment variables. Seems to work so can be closed.
https://github.com/replikativ/datahike/pull/177
