### ISSUE TITLE
0.3.0 clojuars built with java 13, can't load in java 8 jvm. 

### ISSUE THREAD

**Issue by FongHou** [replikativ/datahike#165]
Got error "datahike/java/IEntity has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 52.0" .

**Comment by jrwdunham** [comment]
I can second having run into this as well.

**Comment by kordano** [comment]
Thanks @FongHou and @jrwdunham. What Java version would you suggest?

**Comment by kordano** [comment]
I pushed a build with `openjdk version "1.8.0_252"` to `io.replikativ/datahike "0.3.1-SNAPSHOT"`. Let me know if this version is working for you.

**Comment by FongHou** [comment]
Yes, that version resolved the issue.

Thanks!

**Comment by crofty** [comment]
Just a note to say I also ran into this (using Java 11), updating the dep to `io.replikativ/datahike "0.3.1-SNAPSHOT"` has fixed it.

**Comment by kordano** [comment]
Fixed with release `0.3.1`.
