### ISSUE TITLE
ClassNotFoundException clojure.core.async.Mutex

### ISSUE THREAD

**Issue by FongHou** [replikativ/datahike#166]
datahike depends on a very old version of core.async in its dependent tree, which could cause ClassNotFoundException when other libs on classpath depends on newer version of core.async. 

I couldn't figure out where it comes from the dependent tree. Only being able to repreduce the problem by adding datahike in project.clj.

**Comment by kordano** [comment]
Thanks, this is a similar bug to #156

**Comment by FongHou** [comment]
I did some digging. There are two places in the whole datahike dependent tree where core.async is a dependency.

konserve uses [org.clojure/core.async "0.4.490"] release on 2018.11.19
superv.async uses [org.clojure/core.async "0.3.442"] release on 2017.03.14

I'm currently doing this to prevent ClassNotFoundException. Not sure whether it'll break anything for datahike or not.

[io.replikativ/konserve "0.5.1" :exclusions [org.clojure/core.async]]

**Comment by kordano** [comment]
Maybe we could add a task to the underlying libraries. @whilo
