### ISSUE TITLE
Automated Release Process

### ISSUE THREAD

**Issue by TimoKramer** [replikativ/datahike#167]
Since we want to release Datahike more often there should be an automated release process. Which includes:

- [x] unittesting clj
- [x] integrationtesting with all the official backends in-memory, file, PG/JDBC
- [x] integrationtesting with all the official backends LevelDB
- [x] release to Clojars
- [x] release to maven
- [x] central and testable CI config
- [x] documentation 
- [ ] testing cljs
- [ ] performancetesting
- [ ] compliance tests for backends
- [ ] automated tests for replikativ libraries and other products
- [x] datahike-server releases to docker hub

We should also provide a guideline in terms of testing to unofficial/developing backends with an example to use GitHub Actions of CircleCI. We should also provide automated testing for all the libs that are under our control that are used by datahike and probably others.

**Comment by whilo** [comment]
For external backends we should include compliance tests. We already have a version of this in konserve, but it is not done yet. Basically all backends should have to run through the same comprehensive test suite.

**Comment by TimoKramer** [comment]
I personally find it neat to have a CI building and testing my code on a git push. that is already working.

Following that principle it would be convenient to tag a commit and push that tag to github and that would create an artifact and release it on clojars. There was the wish to have SNAPSHOT-releases be released on commits to development-branch and have real releases be built and released on commit on master.

**Comment by TimoKramer** [comment]
storing secrets in circleci is necessary to deploy to clojars: https://circleci.com/docs/2.0/security

**Comment by TimoKramer** [comment]
I created a first draft to try out a semi automated release model here: https://github.com/TimoKramer/datahike/commit/623808ec8ab517a4008b29af8d7681e13a677ff7
please ask for access to the repo if you want to try it. you can release a '.*-SNAPSHOT'-named artifact to clojars when committing on development and you can release a not '.*-SNAPSHOT'-named release when committing on master.

**Comment by TimoKramer** [comment]
tagging should be automatic. need to find a way to do that without uploading a write-key to circleci. local git-hook might be possible.

**Comment by TimoKramer** [comment]
The env vars LEIN_USERNAME and LEIN_PASSWORD shoud be set inside the clojars-deploy context. and removed from the projects.
The env var CIRCLE_TOKEN should be set inside the orb-deploy context.

**Comment by TimoKramer** [comment]
Closing for now and coming back when CLJS-testing is in work
