### ISSUE TITLE
Cost of d/connect and connection pooling

### ISSUE THREAD

**Issue by theronic** [replikativ/datahike#169]
I'm seeing a ~100x performance speedup when calling `(d/connect ...)` once at startup vs. once per request, even without calling `d/release`. I expected a call to `d/connect` to be cheap and pool connections, but I'm glad I benchmarked. Now I'm just worried whether `conn` will survive for extended periods of time? Just putting this out there so people know not to call `d/connect` on every request.

**Comment by kordano** [comment]
Thanks for the info @theronic. I'm working on a remote transactor now with a new connector in Datahike itself. This will include pool connections.

**Comment by whilo** [comment]
@theronic For now you should be aware of https://github.com/replikativ/datahike/issues/123 and not create multiple connections to the same database that you transact upon. This is not hard to fix for the current in-memory version, but @kordano is integrating the Datahike server with global connection management at the moment and therefore it is not done yet. Sorry for the inconvinience, this bug should not have happened.

**Comment by whilo** [comment]
Distributed connection management is now supported with #332. You will only maintain a single connection per JVM even on reconnects, which is fast to retrieve after initial connection.
