### ISSUE TITLE
Speeding up 8-10s import time of `(require '[datahike.api])`

### ISSUE THREAD

**Issue by theronic** [replikativ/datahike#170]
It takes 8-10s seconds for a call to `(require '[datahike.api])` to complete on my dev machine, which feels really long. All my other dependencies, including httpkit and my web application routes takes <1s to load in total.

What is datahike doing that takes so long? How can I speed it up?

**Comment by whilo** [comment]
We are aware of the issue, but are focusing first to improve write throughput. I think it is either loading the `konserve` dependency or the `hitchhiker-tree`. Are you aware of a good approach to measure the namespace dependency loading in Clojure? We can do so manually of course, but it would be helpful to have a better tool, I think.

**Comment by whilo** [comment]
I have not experienced this loading problem anymore with recent releases (it loads in a second or two), so I will close this now. If you still experience it, please reopen!
