### ISSUE TITLE
Implement datahike.connector/transact! for clojure.lang.PersistentHashMap

### ISSUE THREAD

**Issue by geodrome** [replikativ/datahike#173]
I ran into an issue going through day-of-datomic-cloud examples, but with datahike. 

Here is a simplified example:

`(d/transact conn (hash-map :tx-data [{:user/email "john@example.com"}]))` fails with ` Execution error (NullPointerException) at datahike.connector/transact (connector.cljc:71).
null`

This seems to be because `datahike.connector/transact!` is not implemented for `clojure.lang.PersistentHashMap`

The simple workaround is to use `array-map` instead of `hash-map`:

`(d/transact conn (array-map :tx-data [{:user/email "john@example.com"}]))` works as expected.

Not sure if there is a reason to limit implementation to `clojure.lang.PersistentArrayMap` only.

https://github.com/replikativ/datahike/blob/3c81b6facf781c207292f2b8f2af2c3f2e97c4e8/src/datahike/connector.cljc#L60

**Comment by kordano** [comment]
Fixed with #179
