### ISSUE TITLE
d/q returns a clojure.lang.PersistentHashSet vs clojure.lang.PersistentVector in datomic cloud

### ISSUE THREAD

**Issue by geodrome** [replikativ/datahike#174]
Not sure to what extent datahike aims to maintain datomic compatibility, but here is another little issue I ran into: 

`d/q` in datahike returns a `clojure.lang.PersistentHashSet` while in datomic it returns `clojure.lang.PersistentVector`. Of course in both cases the values returned are unique. 

The practical difference is this: if you do some thing like this in datomic cloud:

```
(-> (d/q '[:find ?e:where [?e :some/attr]]
         (d/db conn))
    flatten)
```

;; result is something like:
=> `(1 2 3)`

;; In datahike you get:
=> `()` ;; because calling `flatten` on any set results in an empty seq.

So in datahike you have to call `vec` prior to calling `flatten`:
```
(-> (d/q '[:find ?e:where [?e :some/attr]]
         (d/db conn))
     vec
     flatten)
```

Not a major issue by any means, but wanted to bring it to your attention anyway.

**Comment by TimoKramer** [comment]
This issue can currently not be resolved because returning vectors is a breaking change and needs further investigation aligned with coming changes.
