### ISSUE TITLE
`d/as-of` is broken

### ISSUE THREAD

**Issue by theronic** [replikativ/datahike#185]
Let's transact a product:
```
(:tx-data (d/transact conn [{:db/id -1
                               :product/sku "ABC"}]))
=>
[#datahike/Datom[536870944 :db/txInstant #inst"2020-06-14T12:27:30.874-00:00" 536870944 true]
 #datahike/Datom[102 :product/sku "ABC" 536870944 true]]
```

Let's check if it's there:

```
(d/datoms (d/as-of @conn (java.util.Date.)) :eavt 102)
=> (#datahike/Datom[102 :product/sku "ABC" 536870944 true])
```

Yup, it's there. Now we retract it:
```
(:tx-data (d/transact conn [[:db.fn/retractEntity 102]]))
=>
[#datahike/Datom[536870945 :db/txInstant #inst"2020-06-14T12:28:33.576-00:00" 536870945 true]
 #datahike/Datom[102 :product/sku "ABC" 536870945 false]]
```

Retracted. Is it gone?
```
(d/datoms @conn :eavt 102)
=> nil
```

Yes, but watch what happens when try the same thing using as-of *now*:

```
(d/datoms (d/as-of @conn (java.util.Date.)) :eavt 102)
=> (#datahike/Datom[102 :product/sku "ABC" 536870944 true])
```

The datom is back. So just to be sure, let's query in the future (the year 2030):
```
(d/datoms (d/as-of @conn #inst "2030") :eavt 102)
=> (#datahike/Datom[102 :product/sku "ABC" 536870944 true])
```

The same things happens using `d/q` or `d/datoms`.

**Comment by kordano** [comment]
Thanks for the report. I'll add a test for that and add a fix for it to the roadmap for `0.3.2`.

**Comment by tmpUser2022** [comment]
The bug also take effect when using `:db/retract` on attributes (with or without value), making `as-of` unsuitable to see retractions changes.

Tested as of `io.replikativ/datahike {:mvn/version "0.4.1490"}`

**Comment by jsmassa** [comment]
You are correct, they are equivalent.
