### ISSUE TITLE
Support for return maps [:find ...:keys ...]

### ISSUE THREAD

**Issue by theronic** [replikativ/datahike#186]
Anything on the horizon for return maps? As per [Datomic docs](https://docs.datomic.com/cloud/query/query-data-reference.html#return-maps):

```
;; query
[:find ?artist-name ?release-name
 :keys artist release
 :where [?release :release/name ?release-name]
 [?release :release/artists ?artist]
 [?artist :artist/name ?artist-name]]

;; inputs
db

;; result
#{{:artist "George Jones" :release "With Love"}
  {:artist "Shocking Blue" :release "Hello Darkness / Pickin' Tomatoes"} 
  {:artist "Junipher Greene" :release "Friendship"}
  ...}
```

Would love to have this in Datahike.

**Comment by kordano** [comment]
This will be added with the next patch release `0.3.1` tomorrow. Thanks to @TimoKramer, it was added here #160.

**Comment by TimoKramer** [comment]
closing because of https://github.com/replikativ/datahike/issues/149
