### ISSUE TITLE
Define formatting guidelines across all libraries

### ISSUE THREAD

**Issue by kordano** [replikativ/datahike#198]

**Comment by TimoKramer** [comment]
requirements:
- CLI-tool
- editor plugin (perform aligned indentation on saving) but editor agnostic
- rowbased formatting
- per project config
- remove trailing whitespace
- collapse contiguous blanks
- extraneous whitespace highlighting
- justify args (https://github.com/kkinnear/zprint/blob/master/doc/reference.md#a-note-on-justifying-two-up-printing)??
- line length 120??
- ...

What options are there?
- zprint
- cljfmt

**Comment by TimoKramer** [comment]
zprint uses https://github.com/bbatsov/clojure-style-guide when using `{:style :community}`

**Comment by TimoKramer** [comment]
couldn't make the `defn` and `defmethod` format with `:gt2-force-nl`...don't know why

**Comment by TimoKramer** [comment]
problems is that we need to skip formatting for `q` and `transact` and possibly others because satisfyingly formatting datalog is not possible, seems like

**Comment by TimoKramer** [comment]
cljfmt seems to be more cautious when it comes to formatting datalog. since I did not find a way to format acceptably with zprint and cljfmt just works it seems that cljfmt is our solution.

**Comment by whilo** [comment]
Thanks for working through this! Does the let-binding alignment work well everywhere?

**Comment by TimoKramer** [comment]
cljfmt uses https://github.com/bbatsov/clojure-style-guide for formatting. so I think it aligns with what you expect @whilo . But please take a look at https://github.com/TimoKramer/datahike/commit/628e52804256e1a0da28d4bfc3a381a79cbfdb9b for a complete formatting run on the whole datahike source.

**Comment by TimoKramer** [comment]
I got an answer by the zprint creator on how to avoid reformatting functions with zprint. so zprint might be cool as well. but since cljfmt works good so far, we'll stick with it? what do you think @whilo @kordano ?

**Comment by TimoKramer** [comment]
https://stuartsierra.com/2016/clojure-how-to-ns.html
