### ISSUE TITLE
add FoundationDB integration

### ISSUE THREAD

**Issue by kordano** [replikativ/datahike#21]

**Comment by corporatepiyush** [comment]
it would be great if it is achieved through a pluggable instance of Protocol which respects the generic Key-Value database API semantics.

**Comment by kordano** [comment]
That's the plan with #32

**Comment by FalseProtagonist** [comment]
Am I right to think that this would be the first durable DB backend other than a flat file? If it's equally hard I imagine that dynamodb would provide more reach?

**Comment by whilo** [comment]
@corporatepiyush @FalseProtagonist  Just to give a bit of context. The KV-semantics can usually be mapped to konserve, which is already support for our default index datastructure, the hitchhiker-tree. Writing a DynamoDB backend should be enough to store datahike there (similar to the konserve CouchDB, Redis or Riak backends), but we still need to provide a networked transactor instance to become fully distributed.

**Comment by FalseProtagonist** [comment]
@whilo thanks for the reply, so there are already backends for all those databases? Is there a doc somewhere on how to set them up? + where's the code location in case one wanted to write one for DynamoDB

**Comment by kordano** [comment]
@FalseProtagonist Currently I'm working on the protocols for that. Currently only an in-memory and file-based backend is implemented. I will show you how you could add different backends, once I finished that.

**Comment by whilo** [comment]
The projects are referenced here: https://github.com/replikativ/konserve. Looking at memory and the filestore.clj backend should give you a reasonable idea of how to integrate it. Exposing that in datahike will be comparatively simple. @kordano is working on exposing different index semantics directly, which makes datahike portable beyond the hitchhiker-tree, but I think you want to use DynamoDB just as a blob store, right?

**Comment by kordano** [comment]
Moving that issue to our roadmap.
