### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by apavlo** [replikativ/datahike#212]
I added Datahike to my encyclopedia of databases:

https://dbdb.io/db/datahike

Do you have an SVG logo that I can use for it? Thanks.

-- Andy

**Comment by kordano** [comment]
Hi @apavlo, thanks for adding us to your encyclopedia. We are still in the process of developing a proper logo for Datahike. Once it is finished, we will send you the SVG.

**Comment by apavlo** [comment]
@kordano Do you have a logo yet?

**Comment by TimoKramer** [comment]
Hi @apavlo. Probably that one? https://datahike.io/assets/images/datahike-logo.svg

**Comment by apavlo** [comment]
Golden. Thanks: https://dbdb.io/db/datahike
