### ISSUE TITLE
misuse of transient 

### ISSUE THREAD

**Issue by mpenet** [replikativ/datahike#22]
Hi, 

I was checking out if I can find low hanging fruits/obvious performance optimizations to apply by just reading the code before pulling out a profiler and I stumbled upon this: 

```
(defn into-via-doseq [to from]
  (let [res (transient [])]
    (doseq [x from]  ;; checking chunked iter
      (conj! res x))
    (persistent! res)))
```
It's a bit weird for 2 reasons: 
* `to` is never used, I guess the intent was to use it as a source to `transient`
* while this *might* work because of an implementation detail of vectors, this is a misuse of transient as stated by the doc. It probably doesn't matter much since it's in the tests, but you can simply replace that with (into [] ..) which is both faster (from what I tested) and correct. 

> Transients support a parallel set of 'changing' operations, with similar names followed by ! - assoc!, conj! etc. These do the same things as their persistent counterparts except the return values are themselves transient. Note in particular that **transients are not designed to be bashed in-place**. **You must capture and use the return value in the next call**. In this way, they support the same code structure as the functional persistent code they replace. As the example will show, this will allow you to easily enhance the performance of a piece of code without structural change.

On a side note I found this by grep'ing for use of `doseq` to potentially replace it with `run!` when possible since it hits the reducible path of the source when possible/makes-sense. 
I have a few other things like this that could be easy gains if you are interested by a PR. I can also submit a PR to fix that one.

**Comment by whilo** [comment]
This code is inherited from datascript and I agree that it is a bit odd. We are planning to rebase on the latest version of datascript as it has some fixes and new features. Do you think you could provide a pull-request there? If this is not working out, we can still incorporate the changes here afterwards.

**Comment by mpenet** [comment]
Sure. 
I'll do that. I will try to have a look at hitchhiker-tree as well.

**Comment by whilo** [comment]
That would be nice. We still have to refactor and clean the hh-tree up a bit. I have mostly taken care of the ClojureScript port so far.
