### ISSUE TITLE
long instead of int for entity ids

### ISSUE THREAD

**Issue by maxweber** [replikativ/datahike#221]
First of all thanks a lot for starting Datahike and working towards an open-source Datomic-like database :+1: 

I've done a few experiments with Datahike and tried to import some real world data from Datomic. I noticed that Datahike is still using `int` as type for the entity id in `datahike.datom/Datom`. Would it make sense to switch to `long`?

Best regards,

Max

**Comment by jsmassa** [comment]
Introduced with release 0.4.1485.
