### ISSUE TITLE
datahike on Andriod app?

### ISSUE THREAD

**Issue by philoskim** [replikativ/datahike#24]
Could anyone tell me if datahike can be used in Android app on react native?

If not, any plan to support Android?

**Comment by whilo** [comment]
Hey @philoskim. We have plans to support Android through react native, but unfortunately we are not there yet. The biggest blocking issue is to port the datahike query engine to support async IO. For what would you like to use datahike on Android?

**Comment by philoskim** [comment]
Thanks for your reply. I am looking for the replacement for sqlite DB which supports datomic-like query, 
 because unfortunately Datascript doesn't support durability.
