### ISSUE TITLE
`:db/retract` without value fails

### ISSUE THREAD

**Issue by xz-stjude** [replikativ/datahike#241]
Datomic (on-prem)'s `:db/retract` has the following [very convenient behavior](https://docs.datomic.com/on-prem/transactions.html#retracting-data):

> To retract data from an existing entity, build a transaction using :db/retract, an existing entity id or entity identifier, the attribute, and optionally value being retracted. If a value is not provided, **all values for the provided entity and attribute will be retracted**.

This is currently not supported in Datahike. Reproducible example:

```
(d/transact conn [{:db/ident :universe
                   :answer   42}])

;; This doesn't work
(d/transact conn [[:db/retract :universe :answer]])
;; => clojure.lang.ExceptionInfo: Cannot store nil as a value at [:db/retract :universe :answer]

;; This works
(d/transact conn [[:db/retract :universe :answer 42]])
```

**Comment by TimoKramer** [comment]
Thanks for reporting @xz-stjude.

**Comment by ema-fox** [comment]
Looking at the relevant [code in db.cljc](https://github.com/replikativ/datahike/blob/f24eda741c85e117e96944afee648438b7f69431/src/datahike/db.cljc#L1759) it seems to me that this behavior is already implemented in `:db.fn/retractAttribute`.

An open question is if `:db/retract` without value arg should recursively retract components like `:db.fn/retractAttribute` does. I didn't find any guidance on this in the datomic documentation and have no datomic instance at hand to try it out.
