### ISSUE TITLE
Formatting rules colliding with Intellij auto-formatting

### ISSUE THREAD

**Issue by TimoKramer** [replikativ/datahike#249]
There is a problem with auto-formatting on Intellij on let-bindings. Is there a setting in Intellij to avoid that?

**Comment by jsmassa** [comment]
How do you set the formatting rules to comply with our guidelines in general?

I have only found the standard Intellij way via settings->editor->codestyle->clojure. I couldn't find the right settings to comply with our guidelines though. But it looks like you can set the indentation for different core functions under the tab "Form Parameters".

**Comment by TimoKramer** [comment]
Currently it is default cljfmt formatting and there is nothing specified though this is possible. I heard that Intellij is formatting differently especially the let-bindings and I wanted to know from Intellij-users if this can be adjusted to not having a lot of reformatting in the PRs. I don't know where this reformatting was that @kordano mentioned. 

Either the intellij-users set the formatting for the let-bindings in their IDE or we need to specifiy the formatting rule in cljfmt and reformat all again. It would be cumbersome for reviewers to have PRs doing the reformatting here and there, I guess.

**Comment by TimoKramer** [comment]
https://github.com/replikativ/datahike/pull/236/files#diff-24742157a2cef9db99aa63817dda341a1d110787835b4a18ac27aa95c9bcc529R109-R116

**Comment by TimoKramer** [comment]
discussion on this in the [clojure style guide](https://github.com/bbatsov/clojure-style-guide/issues/10) that we follow so far

**Comment by jsmassa** [comment]
Ah, ok, that's the formatting you mean... And yes, the forcing of alignment of let binding values can be turned off and on in settings as well in Intellij
