### ISSUE TITLE
Indexed UUIDs are sorted inconsistently breaking some lookup refs

### ISSUE THREAD

**Issue by ajoberstar** [replikativ/datahike#258]
I've been trying out datahike and was trying to use a UUID with unique identity to simplify retrievals and upserts. Due to what appear to be ordering inconsistencies, UUIDs starting with 0-7 are basically lost in the index and 8-f are findable.

I was trying to trace through the code to see where this is happening, but couldn't find anything that seemed convining. However, it does seem like the index order from insertions (evidenced from the `datoms` call) is inconsistent with the lookup ref (index retrieval) behavior. Seems like retrieval uses the key-compare sort, but insertion uses the vanilla Java sort.

See this reproducible example (only needs the datahike 0.3.2 dep).

```clojure
(ns user
  (:require [datahike.api :as d]
            [hitchhiker.tree.key-compare :as kc]))

(def db-cfg {:name "uuid-sort" :store {:backend :mem}})

(defn reset-db! []
  (if (d/database-exists? db-cfg)
    (d/delete-database db-cfg))
  (d/create-database db-cfg)
  (let [db (d/connect db-cfg)]
    (d/transact db [{:db/ident :my-uuid
                     :db/valueType :db.type/uuid
                     :db/unique :db.unique/identity
                     :db/cardinality :db.cardinality/one}])
    db))

(def uuids [#uuid"278d20d2-365b-3653-a2ad-92a161658d96"
            #uuid"d333047d-f17f-34ca-b5d8-ca36a18d61bd"
            #uuid"c0a345d3-dcd6-4e59-a53a-0b3693abc3e7"
            #uuid"b38225b8-8e5f-42aa-bcdc-7bae5b5bdab3"
            #uuid"ad8edc88-6390-4335-b93f-250ee0535ca9"
            #uuid"898b645e-eed2-490a-8ce2-0e7a4d2d5bc8"
            #uuid"50bfd9b9-b5a5-4f25-ad19-b0b129d14267"
            #uuid"c7673c66-c984-450d-8d04-10e9fb2e91ed"
            #uuid"ae9b8279-3959-48d8-8a88-741a7f6d4a48"
            #uuid"27bfa6da-9228-3b4e-b5d4-68a60109077f"
            #uuid"7b29cb4d-f383-4fa8-bc65-0d5e62bd7285"
            #uuid"0b2b7438-5ca2-42ce-824a-f93e031449a3"
            #uuid"50bfd9b9-b5a5-4f25-ad19-b0b129d14267"
            #uuid"8b1a5fa6-6751-304f-9889-296f7fa3c69e"
            #uuid"eafa33f9-aa46-4f5f-9da7-10a7b55246ad"
            #uuid"9d83ad36-04c1-43de-b4aa-039b1e78dfcb"
            #uuid"0211756e-139e-4b4c-a721-9ee9db363f12"
            #uuid"fc183d05-8ef9-4e41-8e22-f815fd3800ea"
            #uuid"50bfd9b9-b5a5-4f25-ad19-b0b129d14267"
            #uuid"3b53c3ba-a879-33a0-9ab4-b5a181973b01"
            #uuid"36283954-733e-4531-96ac-c19e7c9e42d8"
            #uuid"92d142c4-da36-49e0-891e-fc97c9822dba"
            #uuid"50bfd9b9-b5a5-4f25-ad19-b0b129d14267"
            #uuid"df9a6535-528d-3dd0-86fd-88a7fcf14fef"
            #uuid"83c8528f-30ff-4e2a-b0c8-dcc9d6afb448"
            #uuid"bbb61139-9ed8-428a-b702-12c70f0cd910"
            #uuid"0211756e-139e-4b4c-a721-9ee9db363f12"
            #uuid"50bfd9b9-b5a5-4f25-ad19-b0b129d14267"
            #uuid"28b7e811-923a-3910-ab62-05052896a4ab"
            #uuid"0d6e15e3-b839-40c9-941f-b3e64bc06e0f"
            #uuid"732dbf5e-8f11-48b3-a294-6ad0a31642cb"
            #uuid"0211756e-139e-4b4c-a721-9ee9db363f12"
            #uuid"50bfd9b9-b5a5-4f25-ad19-b0b129d14267"
            #uuid"a99fa863-9bce-396f-8b25-525abebe6555"
            #uuid"4e3e6737-a0d1-4162-b71a-9fe4286abd10"
            #uuid"d7bcc8ed-001a-443c-bc47-a4ee5d72f04c"
            #uuid"0211756e-139e-4b4c-a721-9ee9db363f12"
            #uuid"50bfd9b9-b5a5-4f25-ad19-b0b129d14267"
            #uuid"82b477a9-a764-3c09-8220-d88adb378cf0"
            #uuid"981bf128-4bbf-4d84-a337-6f877b4fced0"
            #uuid"83eeaed8-dbb2-41cd-aa11-8bf63db82170"
            #uuid"b7ef058e-6d83-4ca4-8123-9724bff4648b"
            #uuid"65c97e89-b42b-45c2-a70e-0eca1b8f0ff7"
            #uuid"6a1ba2f9-1e5b-446f-9ffa-c0b0963aa08f"
            #uuid"a715278f-1580-409f-8078-4ffbc800e08b"
            #uuid"2377ff19-83e7-4873-b425-dce6d1ad4ef4"
            #uuid"56407f9d-3398-4bf3-bbbd-ea372fa5adeb"
            #uuid"0e3fc579-2d24-4f20-9dae-736e1ec78798"
            #uuid"166be36f-febb-4523-a005-1fb3603bd3f6"
            #uuid"f729e6f8-30dc-4b81-9ff4-f4e7de82225d"
            #uuid"e65ee097-180e-3116-8b68-599b177947b8"
            #uuid"0e3fc579-2d24-4f20-9dae-736e1ec78798"
            #uuid"4d1ac213-d9a2-4377-ab43-9d832281f3a9"])

(defn insert-all [db]
  (d/transact db (into [] (map #(assoc {} :my-uuid %) (shuffle uuids)))))

(defn query-low [db]
  (d/q {:query '{:find [(pull ?e [*])]
                 :in [$ ?id]
                 :where [[?e :my-uuid ?id]]}
        :args [@db #uuid"278d20d2-365b-3653-a2ad-92a161658d96"]}))

(defn lookup-low [db]
  (d/pull @db '[*] [:my-uuid #uuid"278d20d2-365b-3653-a2ad-92a161658d96"]))

(defn lookup-high [db]
  (d/pull @db '[*] [:my-uuid #uuid"83c8528f-30ff-4e2a-b0c8-dcc9d6afb448"]))

(defn datoms [db]
  (d/datoms @db :avet :my-uuid))

(defn compare-clj []
  (compare #uuid"278d20d2-365b-3653-a2ad-92a161658d96" #uuid"83c8528f-30ff-4e2a-b0c8-dcc9d6afb448"))

(defn compare-hh []
  (kc/-compare #uuid"278d20d2-365b-3653-a2ad-92a161658d96" #uuid"83c8528f-30ff-4e2a-b0c8-dcc9d6afb448"))

(comment
  (def db (reset-db!))

  (insert-all db)

  ;; The "low" test value is in the db
  (query-low db)
  ;; However a lookup ref (i.e. using the avet index) returns nothing
  (lookup-low db)

  ;; but a lookup ref of a "high" test value does return
  (lookup-high db)

  ;; you can see the way the datoms are sorted in the index
  (datoms db)

  ;; this order seems to comply with the standard clj order
  (compare-clj)

  ;; but the hithhiker tree key-compare specified a different order
  (compare-hh)

  ;; seems like its inserting using a different comparator than the lookup uses

  [])
```

**Comment by ajoberstar** [comment]
Also noticed that overriding the UUID behavior in `IKeyCompare` gets it to work consistently (for my dataset).

```clojure
(extend-protocol kc/IKeyCompare
  java.util.UUID
  (-compare [k1 k2]
    (compare k1 k2)))
```

**Comment by markusalbertgraf** [comment]
That might solve #122 too.

**Comment by ajoberstar** [comment]
I think I've tracked it down, and ultimately it's a hitchhiker-tree issue, but it manifests in datahike due to the way it uses the key comparison.

First, hitchhiker-tree's default IKeyCompare includes [custom compare implementations](https://github.com/replikativ/hitchhiker-tree/blob/c582e65b0cf3479e55e40a4505f80e9a2c1be7af/src/hitchhiker/tree/key_compare.cljc#L103-L220) for a number of types, notably *not* including any collection types (particularly PersistentVector).

This means that out-of-box, hitchhiker-tree has inconsistent sorts between comparing UUIDs directly and comparing vectors that include UUIDs.

```clojure
;; Clojure default compare (consistent)
(compare #uuid"278d20d2-365b-3653-a2ad-92a161658d96" #uuid"d333047d-f17f-34ca-b5d8-ca36a18d61bd") ;; 1
(compare [:my-uuid #uuid"278d20d2-365b-3653-a2ad-92a161658d96"] [:my-uuid #uuid"d333047d-f17f-34ca-b5d8-ca36a18d61bd"]) ;; 1

;; Hitchhiker Tree compare (inconsistent
(kc/-compare #uuid"278d20d2-365b-3653-a2ad-92a161658d96" #uuid"d333047d-f17f-34ca-b5d8-ca36a18d61bd") ;; -1
(kc/-compare [:my-uuid #uuid"278d20d2-365b-3653-a2ad-92a161658d96"] [:my-uuid #uuid"d333047d-f17f-34ca-b5d8-ca36a18d61bd"]) ;; 1
```

Datahike makes the choice to extend IKeyCompare to [support PersistentVector](https://github.com/replikativ/datahike/blob/8cecdc13f34b7e3294395eee000213e184376f3e/src/datahike/index/hitchhiker_tree.cljc#L11-L32). With this change calls to `kc/-compare` are now consistent between vectors and raw values.

However, this issue and #122 are cases of sorting behaving one way at insertion time and another way at lookup time. So what's the difference between the two. Especially with the oddities @markusalbertgraf notes in #122 where the quantity of errors changes based on the amount of data you insert.

While the code seems to all use `kc/-compare`, new nodes in the tree are all started from the empty `PersistentTreeSet` [`empty-sorted-map-by-compare`](https://github.com/replikativ/hitchhiker-tree/blob/c582e65b0cf3479e55e40a4505f80e9a2c1be7af/src/hitchhiker/tree.cljc#L160).

```clojure
(def empty-sorted-map-by-compare (sorted-map-by c/-compare))
```

Unlike in all other uses of `c/-compare` in the codebase, this one is passed into the Java layer as a constructor parameter to [`clojure.lang.PersistentTreeMap`](https://github.com/clojure/clojure/blob/f47c139e20970ee0852166f48ee2a4626632b86e/src/jvm/clojure/lang/PersistentTreeMap.java#L55) as a `Comparator`. The map thus sees the unwrapped var of `kc/-compare`, i.e. only what was defined in the protocol at the time `empty-sorted-map-by-compare` is defined.

Extensions of the `IKeyCompare` protocol outside the `hitchhiker.tree.key-compare` namespace alter the var root of the `-compare` method with the new behaviors. Which is why all of the other code that stays in Clojure-land and references the var in it's code sees the new behavior provided by Datahike's `extend-protocol` call.

In practice, this means that insertions into a node's children are always sorted according to the default `IKeyCompare`, which doesn't cover vectors. So in the case of Datahike indices, everything is inserted into a node in the order of default Clojure comparison.

A hacky workaround might be to redef the `empty-sorted-map-by-compare` after loading Datahike's namespaces, but before initializing your database. However, this ultimately probably needs a change to hitchhiker-tree, unless hitchhiker-tree decides it doesn't want to support user-extension of `IKeyCompare`.

Three potential fixes that I can think of:
1. Don't support user-extension of `IKeyCompare` and update default definition to sort collections consistently with the raw value comparisons.
2. Update hitchhiker tree to either create a new empty map for each node
3. Update hitchhiker tree to create a new empty map for each tree (and store it in the `:cfg` for reference by other nodes).

1 has the benefit of promoting the index sorting as part of the contract of hitchhiker-tree. Since in the case of datahike, changing the sort of an index has major backwards-compatibility concerns with existing databases.

2 might be the easiest fix, but may have performance/memory implications.

3 avoids the performance implications but may be a little more work than 2

**Comment by ajoberstar** [comment]
As a hacky workaround until a fix is in place, this is probably better than changing my previous `extend-protocol` suggestion. I would guess that any fix made will involve keeping the sorting of UUID that is set in `IKeyCompare`, so this one will be more likely to give you forward-compatible indices.

Call this before you first create/load a db and it should behave consistently.

```clojure
(alter-var-root #'tree/empty-sorted-map-by-compare (constantly (sorted-map-by kc/-compare)))
```

**Comment by whilo** [comment]
Hey @ajoberstar , thanks a lot for reporting this and tracking it down so quickly! It is very much appreciated, since I have not had the time yet to track down this issue. 

Your explanation makes sense. I decided not to implement collection handlers in the hh-tree repository so far because I did not want to decide too much of the semantics in the hitchhiker-tree itself, but I think it is definitely ok by now to implement collection comparators as well. I would still consider doing 3. as well, since extending the comparator to other custom types outside of the codebase would still be broken otherwise. If you are in the mood of doing either of these things, I would be very happy to merge a PR and fix this issue at this issue.

**Comment by MrEbbinghaus** [comment]
Stumbled across this problem last night. Thought I was going crazy not finding the bug in my code.

**Comment by mainej** [comment]
Note, this is still occurring, even with the 0.3.4 release, possibly because https://github.com/replikativ/hitchhiker-tree/pull/24 was merged into the `development` branch, but not yet to `master`.

**Comment by whilo** [comment]
Yes, the current release was a hotfix for a newly introduced bug with `0.3.3`. We plan our new feature release at the moment including the UUID fix.
