### ISSUE TITLE
error logs appearing when defining schema in SNAPSHOT release

### ISSUE THREAD

**Issue by TimoKramer** [replikativ/datahike#267]
I am getting errors when using `:schema-flexibility :write` on transacting the schema:

```
2020-12-14T17:37:31.285Z foo ERROR [datahike.db:1129] - Schema with attribute :account/id does not exist {:error :retract/schema, :attribute :account/id}
```

This applies to the current SNAPSHOT 0.3.3-SNAPSHOT

**Comment by MrEbbinghaus** [comment]
I think this is resolved.

Some later SNAPSHOTs and the current stable don't have the problem anymore.

**Comment by grischoun** [comment]
Yes, this issue has been fixed. Thanks for reporting.
Closing.
