### ISSUE TITLE
tools.reader error on repl start

### ISSUE THREAD

**Issue by NeroVanbiervliet** [replikativ/datahike#27]
On starting a `lein repl`, it crashes. Top of stacktrace: 
```
#error {
 :cause reader-error does not exist
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message Syntax error compiling at (clojure/tools/reader/edn.clj:1:1).
   :data #:clojure.error{:phase :compile-syntax-check, :line 1, :column 1, :source clojure/tools/reader/edn.clj}
   :at [clojure.lang.Compiler load Compiler.java 7647]}
  {:type java.lang.IllegalAccessError
   :message reader-error does not exist
   :at [clojure.core$refer invokeStatic core.clj 4249]}]
 :trace

[...]

```

I found out that a very old version of `org.clojure/tools.reader` is used. Relevant part of `lein deps :tree`:
```
[io.replikativ/datahike "0.1.3"]
   [io.replikativ/hitchhiker-tree "0.1.4"]
     [com.taoensso/carmine "2.12.2"]
       [com.taoensso/encore "2.32.0"]
         [com.taoensso/truss "1.0.0"]
         [org.clojure/tools.reader "0.10.0"]
```

**Comment by whilo** [comment]
Ok, thanks for reporting. We will fix this in the hh-tree dependencies. Do you know that you can override that?.

**Comment by NeroVanbiervliet** [comment]
Thanks! You mean by adding `tools.reader` myself as a dependency? If i do so `[org.clojure/tools.reader "1.3.2"]`, I get a different error: 
```
WARNING: pos-int? already refers to: #'clojure.core/pos-int? in namespace: taoensso.encore, being replaced by: #'taoensso.encore/pos-int?
WARNING: bytes? already refers to: #'clojure.core/bytes? in namespace: taoensso.encore, being replaced by: #'taoensso.encore/bytes?
#error {
 :cause Must hint overloaded method: toArray
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message Syntax error compiling deftype* at (datahike/btset.cljc:423:1).
   :data #:clojure.error{:phase :compile-syntax-check, :line 423, :column 1, :source datahike/btset.cljc, :symbol deftype*}
   :at [clojure.lang.Compiler analyzeSeq Compiler.java 7114]}
  {:type java.lang.IllegalArgumentException
   :message Must hint overloaded method: toArray
   :at [clojure.lang.Compiler$NewInstanceMethod parse Compiler.java 8496]}]
 :trace

[...]
```

**Comment by NeroVanbiervliet** [comment]
Ok, found out about `:exclusions`, but ended up having more errors.

**Comment by whilo** [comment]
Right I see. I guess this is because we use an outdated ClojureScript version.

**Comment by kordano** [comment]
I will have a look and try to fix this.

**Comment by bzg** [comment]
Just to add another input on this: using `[org.clojure/core.async "0.4.490" :exclusions [org.clojure/tools.reader]]` in the project.clj's dependencies works for me with java `openjdk version "1.8.0_191"`.

The `:cause Must hint overloaded method: toArray` seems unrelated to the `tools.reader` issue, it is most probably an issue with using `java =>11`.

**Comment by NeroVanbiervliet** [comment]
Currently, I'm using datahike version `0.2.0-beta` (available on clojars) and all is well on openjdk 1.
