### ISSUE TITLE
Slow transact

### ISSUE THREAD

**Issue by jeans11** [replikativ/datahike#284]
Hi!

I'm currently testing Datahike and I found the transact (on file storage) slower for just one item

<img width="1266" alt="Screenshot 2021-02-06 at 18 15 44" src="https://user-images.githubusercontent.com/7700239/107224944-71722f00-6a18-11eb-9176-abdfdb09e079.png">

It's normal?

I store the db in `/tmp` on a MacBook pro (2015)

**Comment by whilo** [comment]
Hey, @jeans11! Can you explain what you exactly compared and what was slower? I get the sense that you transacted individually and in batch, but I am not sure.

**Comment by jeans11** [comment]
Hi @whilo! 
After spending few minutes to clean my laptop memory, I don't have slow transact anymore.
Sorry for the inconvenience but I think the issue was my laptop.
Now everything works perfectly!
Thx
