### ISSUE TITLE
protorepl and datahike: dependency issue 

### ISSUE THREAD

**Issue by bennoloeffler** [replikativ/datahike#286]
Hi everyone,
I tried datahike in atom with protorepl and found that those dependencies crash:

```
(defproject dh_example "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.10.1"]
                 [io.replikativ/datahike "0.3.3"]
                 [org.clojure/tools.namespace "1.1.0"]
                 [proto-repl "0.3.1"]]
```

They result in:
`Syntax error macroexpanding clojure.core/refer-clojure at (clojure/core/async.clj:9:1)`
(and a huge stacktrace)

Because:
current [proto-repl "0.3.1"] depends on [org.clojure/core.async "0.2.374"] 
current [datahike "0.3.3"] depends on [org.clojure/core.async "1.3.610"]

`lein deps :tree`
suggests 
`[io.replikativ/datahike "0.3.3" :exclusions [org.clojure/core.async]]
`
But that obvoiusly does not help - because then the old core.async is still in use.

Instead, this helps:
`[proto-repl "0.3.1" :exclusions [org.clojure/core.async]]`

So the dependencies look like:
```
(defproject dh_example "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.10.1"]
                 [io.replikativ/datahike "0.3.3"]
                 [org.clojure/tools.namespace "1.1.0"]
                 [proto-repl "0.3.1" :exclusions [org.clojure/core.async]]] 
```

I like datahike, atom and protorepl - therefore, this hint may help some others newbies to get started.

**Comment by TimoKramer** [comment]
thanks @bennoloeffler! now people can find this here. that indeed could help someone with the same problem. :+1:
