### ISSUE TITLE
upsert fails on variations of previously replaced values

### ISSUE THREAD

**Issue by markusalbertgraf** [replikativ/datahike#289]
Hi!

I stumbled over this bug while upserting oauth2-access-tokens which are strings and need to be refreshed every 60 minutes.

These tokens all start with the same character sequence.

Upsert of string values may fail when
1. A previously deleted value is a left sub-string of the new value.
2. The db is above a certain size.

To clarify 1):  "Markus" can be upserted to "Markus1" but then further upserting to "Markus" will fail.

I have created a project that provides the following
1. A function that does a series of upserts and pulls to document the behavior.
2. A function that builds bigger and bigger databases until it provides one that displays the buggy behavior.

https://github.com/markusalbertgraf/dh-upsert-bug-hunter

**Comment by grischoun** [comment]
Hi @markusalbertgraf,

Thanks for reporting the issue and also for taking the time to create the project. It is going to be very helpful.
I'll have a look at it very soon.

**Comment by markusalbertgraf** [comment]
As @whilo suggested I checked the indices as provided by d/datoms.
:eavt and :aevt contain only the latest state.
:avet contains (maybe) all current and previous states.  Even with multiple identical entries if transactions have been repeated.

**Comment by grischoun** [comment]
@markusalbertgraf we found out the source of the issue and are now working on a fix.

**Comment by grischoun** [comment]
Hi @markusalbertgraf,

We have the fix ready. But before deploying, we would like to make sure that it works for you. 
Would you be able to try on your application with the fixed branch, i.e., https://github.com/replikativ/datahike/tree/289-upsert-fails-on-repeated-value ?

**Comment by grischoun** [comment]
@markusalbertgraf We have released a new version of Datahike (0.3.4) with the fix I mentioned in my previous message. 

I am closing the issue. Feel free to reopen it if we missed something.

**Comment by markusalbertgraf** [comment]
Thank you!!!
And sorry I missed your mention 3 days ago.

**Comment by grischoun** [comment]
No problem.

There was a dependency issue with v.03.4 and v.0.3.5 has been released to fix the issue.
https://clojars.org/io.replikativ/datahike/versions/0.3.5
