### ISSUE TITLE
Replication backends

### ISSUE THREAD

**Issue by knubie** [replikativ/datahike#295]
I apologize for using Github Issues as a discussion forum, but this seemed like the most appropriate place to bring it up. I've been following datahike for some time now and I'm really excited about the progress being made recently, especially with the Clojurescript support.

At the moment I use the Pouchdb/Couchdb combo for a local-first approach for my application. I really love the "backend adapter" approach that both PouchDB and Datahike use. Recently I was looking at RxDB, which is a library built on top of PouchDB with some extra features. One of those extra features is support for replication over GraphQL. This opens up the possibility of replicating not just to CouchDB, but any other database so long as the GraphQL interface is implemented.

I think this is a really powerful idea and seems very similar in spirit to the agnostic protocol-based approach of durable storage that Datahike uses.

Anyway, I just wanted to bring this up as food for thought.

**Comment by knubie** [comment]
I've also been doing some research around this area of local-first databases, particularly around react and how they might interact / compare with existing state management solutions. I've been compiling my research in a zettelkasten notebook in case you're interested: https://app.mochi.cards/decks/matt/dscynl21e34EFFr/Databases

Btw I've also noticed on the blog post about CLJS integration that you're partnering with Homebase. I wonder what the relationship is between these two projects?

**Comment by whilo** [comment]
Hey @knubie , thanks for reaching out! Homebase is sponsoring part of our ClojureScript work and we are closely collaborating with them on frontend dev tooling for Datalog at the moment. I am also friends with one of the cofounders and we in general have a high value alignment and similar long-term goals for a distributed open-source infrastructure for more adaptive and democratic social processes. The GraphQL synchronisation sounds interesting and your notes seem to have a large overlap with what we are interested in. Can you join our discord server and ping me there to continue the discussion? https://discord.gg/kEBzMvb
