### ISSUE TITLE
Remove hard ClojureScript dependency?

### ISSUE THREAD

**Issue by kommen** [replikativ/datahike#302]
I'm using datahike server-side only, however it still brings in a hard ClojureScript dependency via `hitchhiker-tree`, `konserve` and others which  I believe is unnecessary:

```
$ clj -Sdeps '{:deps {io.replikativ/datahike {:mvn/version "0.3.5"}}}}' -Stree | grep clojurescript                
    . org.clojure/clojurescript 1.10.773 :newer-version
        X org.clojure/clojurescript 1.10.339 :older-version
        X org.clojure/clojurescript 1.9.89 :older-version
          X org.clojure/clojurescript 1.7.170 :older-version
  X org.clojure/clojurescript 1.10.597 :superseded
```

Many libraries prevent this by specifying their ClojureScript dependency as `:scope "provided"`.

**Comment by TimoKramer** [comment]
Hi @kommen . Afaik clj-tools [does not (yet) support scope for deps.](https://ask.clojure.org/index.php/9110/scope-in-deps-edn-should-be-added-and-not-deleted-from-pom-xml)
I am thinking about using an alias here for cljs but making cljs a second class citizen here is maybe not the right approach, so I am open for suggestions here. Of course a PR is always very much appreciated.

**Comment by kommen** [comment]
Thank you, I didn't know that tools.deps didn't support that. I guess there is very little to be done here then for now.

**Comment by TimoKramer** [comment]
Looking at [meander](https://github.com/noprompt/meander/blob/epsilon/deps.edn) and [promesa](https://github.com/funcool/promesa/blob/master/deps.edn) it seems like an approach is to put clojure and clojurescript into the dev alias. Do you want to try that out and make a PR for it?
