### ISSUE TITLE
Remove unnecessary dependencies

### ISSUE THREAD

**Issue by whilo** [replikativ/datahike#31]
Currently datahike automatically pulls in ClojureScript, timbre, guava and a few other things. We should make these dependencies optional by going through our stack. This will also make it easier to have datahike run on GraalVM. @borkdude

**Comment by kordano** [comment]
With the rebase I started cleaning and updating the dependencies too. Maybe we should also clean up the deps in our other libraries like konserve or hitchhiker tree.

**Comment by borkdude** [comment]
I think stripping unnecessary deps is always a good thing, but I'm not sure if this will speed up GraalVM compilation.

**Comment by whilo** [comment]
> With the rebase I started cleaning and updating the dependencies too. Maybe we should also clean up the deps in our other libraries like konserve or hitchhiker tree.

Yes, definitely. That is what I thought. My take is to declare the dependencies with `:scope-provided` in leiningen, but I guess it is better to move to `deps.edn`? I am a bit out of date with respect to current tooling.

**Comment by kordano** [comment]
Agreed, we should try it with `deps.edn`.

**Comment by kordano** [comment]
with the datascript rebase we have a `deps.edn` as a starting point: https://github.com/replikativ/datahike/blob/28-datascript-rebase/deps.edn
