### ISSUE TITLE
Benchmarks error

### ISSUE THREAD

**Issue by den1k** [replikativ/datahike#312]
Tried on `master` and `development`
```
➜  datahike git:(master) clj -A:benchmark
Syntax error (ClassNotFoundException) compiling at (datahike/impl/entity.cljc:1:1).
datahike.java.IEntity

Full report at:
/var/folders/0l/rm9ggfzd5457q6c5_sy182m40000gn/T/clojure-7677209848210039311.edn
```

**Comment by TimoKramer** [comment]
Hi @den1k . Please try to run `mvn compile` first. That should do the trick! Please close this if it works for you.

**Comment by TimoKramer** [comment]
And please feel free to improve the docs: https://cljdoc.org/d/io.replikativ/datahike/0.3.5/doc/contributing-to-datahike

**Comment by den1k** [comment]
Thanks @TimoKramer that works. The docs you linked to are fine. But the mvn command is missing in the readme: https://github.com/replikativ/datahike#performance-measurement
