### ISSUE TITLE
Benchmark cli opts don't work?

### ISSUE THREAD

**Issue by den1k** [replikativ/datahike#313]
```
➜  datahike git:(master) clj -M:benchmark --db-datom-counts '[20000]' --iterations 2 --tx-datom-counts '[20000]'
Errors: [Unknown option: "--db-datom-counts" Unknown option: "--iterations" Unknown option: "--tx-datom-counts"]
Usage: clj -M:benchmark [options]

  Options:
  -u, --db-server-url URL  nil  Base URL for datahike server, e.g. http://localhost:3000
  -n, --db-name DBNAME     nil  Database name for datahike server
  -g, --db-token TOKEN     nil  Token for datahike server
  -t, --tag TAG            #{}  Add tag to measurements
  -h, --help
  ```

opts source: https://github.com/replikativ/datahike/blob/development/benchmark/src/benchmark/core.clj#L27-L32

**Comment by whilo** [comment]
I can run this command `clj -A:benchmark --db-datom-counts '[20000]' --iterations 2 --tx-datom-counts '[20000]' run` on the current `master` and `development` branches. I think you were mixing up `-M` with `-A` here. Does this provide what you need?

**Comment by den1k** [comment]
That works. Should the docs here also use `-A`?:

https://cljdoc.org/d/io.replikativ/datahike/0.3.5/doc/contributing-to-datahike#starting-the-benchmark

**Comment by whilo** [comment]
I guess so, what do you think @TimoKramer ?

**Comment by den1k** [comment]
Tried running benchmarks with a large DB but it kept failing and running out of heap space even after I increased it to 12gigs and wrote to disk:

```
datahike git:(development) clj -J-Xmx12g -A:benchmark -c file --db-datom-counts '[200000]' --iterations 2 --tx-datom-counts '[10]' run


Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "async-thread-macro-767"
Exception in thread "async-thread-macro-385" Exception in thread "async-thread-macro-317" java.lang.OutOfMemoryError: Java heap space
Exception in thread "clojure.core.async.timers/timeout-daemon" java.lang.OutOfMemoryError: Java heap space
Exception in thread "async-thread-macro-553" java.lang.OutOfMemoryError: Java heap space
Exception in thread "async-thread-macro-838" java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
Execution error (OutOfMemoryError) at (REPL:1).
Java heap space

```

Any idea how to run these properly? I mostly care about the query benchmarks.

**Comment by jsmassa** [comment]
I ran into this issue a few days ago as well. Unfortunately, we currently don't have the capacities to investigate the memory problem though as the work on actual query performance improvement has highest priority at the moment.
The benchmarks are also still under construction. I am currently working on the option to restrict the benchmarks to the aspect you actually want to investigate, maybe that will also allow it to work on a bit bigger databases. I can notify you when this is done, so you can try.

**Comment by TimoKramer** [comment]
Hi @den1k, sorry for not seeing your issue here. I am using the latest clojure-tools version `Clojure CLI version 1.10.3.822` and for me it works like intended. Probably update it?
You can set the max heap space like so:
`clj -J-Xmx8G -M:benchmark  --db-datom-counts '[20000]' --iterations 2 --tx-datom-counts '[20000]' run`

**Comment by jsmassa** [comment]
For me it works as well. And I think I got deprecation warnings for the `-A` flag. I am sure `-M` is the right choice with the current CLI version. See also [here](https://stackoverflow.com/questions/66925857/when-to-use-m-a-or-x-with-clojure-cli).

**Comment by grischoun** [comment]
For info, it also worked for me. But I had to increase the heap to 20G. 
`clj -J-Xmx20G -M:benchmark --db-datom-counts '[20000]' --iterations 2 --tx-datom-counts '[20000]' run`

**Comment by den1k** [comment]
Can anyone get it to run with 200K --db-datom-counts?

**Comment by den1k** [comment]
Datahike is making art:

![image](https://user-images.githubusercontent.com/4651810/117159571-02417800-ad86-11eb-8ed2-9a3a6fecbb67.png)

**Comment by jsmassa** [comment]
Is that the output from the timbre logging for the transaction? I got some beautiful wave patterns from that as well the other day ^^
I think, the default timbre level is still on debug, which is not optimal. you can change it by setting the environment variable `TIMBRE_LEVEL=":warn" ` for example. 

Still, I wouldn't even try for 200000 datoms in this version of the benchmarks. Even if it did work space-wise I expect it to take some hours.

**Comment by den1k** [comment]
Keep running out heapspace when trying 200K datoms, even with 20 gigs of heap space and file storage only :/ (can successfully run 20K)

```clj -J-Xmx20G -M:benchmark -c file --db-datom-counts '[200000]' --iterations 2 --tx-datom-counts '[20]' run```

**Comment by den1k** [comment]
Closing this issue, since I should just benchmark this for my use case. Thanks for all the help!

**Comment by whilo** [comment]
Ok, feel free to come back with suggestions for improvements of the benchmarks. We try to get it right, which requires navigating many different trade-offs. Having real use cases being contributed is definitely helpful.
