### ISSUE TITLE
blocking forever on corrupted database

### ISSUE THREAD

**Issue by awb99** [replikativ/datahike#317]
The call d/database-exists and d/connect keeps blocking forever.
This is caused by a corrupted database file.
I dont know exactly what caused the db to get corrupted.
But what I would expect is some kind of exception.
Hanging forever is never good.

**Comment by whilo** [comment]
Yes, that should never happen. Can you look at the stack in a profiler such as VisualVM and see where it is hanging?

**Comment by awb99** [comment]
I have already deleted the corrupted database.
If I will recreate a similar fuckup, then I will save the database and upload it somewhere.
