### ISSUE TITLE
1 writer, n reader

### ISSUE THREAD

**Issue by awb99** [replikativ/datahike#322]
I cannot find a forum to ask questions for, so I put the question in here:

Is it safe to have multiple connections with one writer app and n reader apps connected to the
same file storage? Will the readers pick up new data?

**Comment by whilo** [comment]
Yes, this post is describing how you can have multiple readers and one writer with shared file storage at the moment: https://lambdaforge.io/2019/12/08/replicate-datahike-wherever-you-go.html. If you have a shared file system you can ignore the Dat related bits and just run multiple peers on the same shared filesystem. We will automate the refreshing of the connection from the store in our next releases based on our newly added transactor interface and datahike-server, so you will not have to add the refreshing code manually.
