### ISSUE TITLE
paging

### ISSUE THREAD

**Issue by awb99** [replikativ/datahike#326]
This is perhaps a stupid question. But say the data returned from a query is big,
is there a way to return pages? Most database have a feature like that, so wondering
how to deal with this in datahike.

**Comment by whilo** [comment]
We support paging, but so far it is rerunning the query completely each time and not allowing you to lazily step over results. You can see examples here with `page` and `offset` https://cljdoc.org/d/io.replikativ/datahike/0.3.6/api/datahike.api#q that follow the Datomic paging API. Using this API you will benefit from more efficient paging as soon as we upgrade our query engine for lazy result loading.

**Comment by awb99** [comment]
Nice! Thank you!
