### ISSUE TITLE
GraalVM native image support

### ISSUE THREAD

**Issue by whilo** [replikativ/datahike#336]
The stack of Datahike is very self-contained and therefore particularly interesting for a native-image.

**Comment by awb99** [comment]
Babashka has a pod api. Perhaps @borkdude could help to add datahike to babashka

To mw the combination of datahike and babashka sounds like a great combo. 
Then one could do ad-hoc queries to datahike databases from the shell.

**Comment by borkdude** [comment]
Maybe you can take a look at datalevin, which already exposes itself as a babashka pod:

https://github.com/juji-io/datalevin#babashka-pod

**Comment by whilo** [comment]
This was solved with #337. We discussed deeper Babashka integration as future work, but the command line client should already work well with it now.
