### ISSUE TITLE
datahike.api should export its functions properly

### ISSUE THREAD

**Issue by whilo** [replikativ/datahike#34]
Currently the argument lookup and documentation does not work for the aliases in `datahike.api`. They should be properly aliased.

**Comment by kordano** [comment]
I would recommend fixing that with #26

**Comment by kordano** [comment]
At some point we should merge core and api namespace. I will add another task for that.

**Comment by whilo** [comment]
I left core and api separate, because api is actually the datomic api. I thought core would support core.async at some point for cljs, whilo datahike.api will always be sync. We can also merge them and have separate functions for each case.

**Comment by whilo** [comment]
Fixed with 0.2.0 release.
