### ISSUE TITLE
refactor test namespaces

### ISSUE THREAD

**Issue by kordano** [replikativ/datahike#342]
- [x] move from `datahike.core` to `datahike.api`
- [x] move to `X-test` namespace formats
- [x] update integration tests to use all api-functions
- [ ] evaluate test generation with `clojure.spec`
- [ ] use fixture to run different config on same tests (see tx_log-test)
- [x] use random db-ids
- [x] move config from string to hash-map and use util-fn
- [x] remove `with` from core and adapt api-ns to reflect functionality
- [x] call empty-db from db-ns

**Comment by TimoKramer** [comment]
with-macro possibly to use different configs or best would be to automate different configs.

**Comment by TimoKramer** [comment]
touch to pull with `(d/pull db '[*] 1)`
