### ISSUE TITLE
Extend `hitchhiker.tree.node/IEDNOrderable` to `clojure.lang.IFN`?

### ISSUE THREAD

**Issue by fahtative** [replikativ/datahike#389]
Apparently "type not supported" is threw when I tried to use transaction function, installed with a tx: `{:db/ident ... :db/fn <fn>}`. The same error occurs when reading the function from the db (with read schema-flexibility). Extending `hitchhiker.tree.node/IEDNOrderable` to `clojure.lang.IFN`, following [this]( https://github.com/replikativ/hitchhiker-tree/blob/master/src/hitchhiker/tree/key_compare.cljc), seems to work. Should this be the solution or is there a way to use transaction function I missed?

**Comment by fahtative** [comment]
Ah. I guess it doesn’t make sense to “install” runtime functions like that. Anyhow, how should I approach database functions in datahike?

**Comment by whilo** [comment]
At the moment the transactor lives in the same process as is the case in DataScript. So you can just call into functions directly. Once our distributed transactor is there we will have to provide a way to store the code in Datahike and `eval` it on each peer as needed. Does this cut it for you or do you already work in a distributed setting with Datahike?

**Comment by fahtative** [comment]
I see. I understand now that I should wrap function call like this: `[:db.fn/call <fn> ...]`, as documented by Datascript. I'm not working in distributed setting yet, but that sounds promising! Looking forward to it...
