### ISSUE TITLE
[Bug]: Missing tx-meta on transact via api-ns

### ISSUE THREAD

**Issue by TimoKramer** [replikativ/datahike#433]
### What version of Datahike are you using?

0.3.6

### What version of Java are you using?

11.0.13

### What operating system are you using?

Linucz

### What database EDN configuration are you using?

```edn
{:store {:backend :mem 
            :id (str (UUID/randomUUID))}
  :keep-history? true
  :schema-flexibility :read}
```

### Describe the bug

```clojure
(require '[datahike.api :as d]
         '[datahike.test.utils :as **du])
(deftest test-tx-meta
  (let [conn (du/setup-db)
        tx   (d/transact conn {:tx-data [{:name "Sergey"
                                          :age  5}]
                               :tx-meta {:foo "bar"}})]
    (is (= (:tx-meta tx)
           {:foo "bar"}))))
```
This fails when but should succeed. connector-ns only transacts the tx-data in the `transact!`-fn

### What is the expected behaviour?

It should show the tx-meta properly

### How can the behaviour be reproduced?

see above

**Comment by TimoKramer** [comment]
Reinstate tests in test/datahike/test/listen_test.cljc and test/datahike/test/transact_test.cljc when fixed.

**Comment by TimoKramer** [comment]
Do you have any thoughts about fixing this? I would try that.

**Comment by kordano** [comment]
Yes, please go ahead. I started with a first version in a separate branch a couple of months ago with this commit just as a pointer: https://github.com/replikativ/datahike/commit/6d5de14e4823ded71aaf2661525045c80512b2a0

**Comment by TimoKramer** [comment]
https://github.com/replikativ/datahike/pull/460
