### ISSUE TITLE
add storage layer protocols

### ISSUE THREAD

**Issue by kordano** [replikativ/datahike#44]

**Comment by whilo** [comment]
What is the exact purpose of this abstraction? We already support storage layer abstraction through konserve and the index-layer abstractions operate at a layer higher, where the setup of the underlying index already determines the storage layer properties, e.g. FoundationDB.

**Comment by kordano** [comment]
Ok, then we have to document it here in datahike. So people can write their on backends for the database. Maybe I'll add that to my readme/wiki refactoring planned for July.

**Comment by kordano** [comment]
Will be fixed with #37
