### ISSUE TITLE
[Bug]: store max-ent-id in db record

### ISSUE THREAD

**Issue by whilo** [replikativ/datahike#440]
### What version of Datahike are you using?

0.3.7-SNAPSHOT

### What version of Java are you using?

openjdk 11.0.11 2021-04-20

### What operating system are you using?

Ubuntu 20.04

### What database EDN configuration are you using?

-

### Describe the bug

When max-ent-id is not stored in the db record the unit tests in the GraalVM branch fail.

### What is the expected behaviour?

Max-ent-id should not be decremented in these tests.

### How can the behaviour be reproduced?

Look at https://github.com/replikativ/datahike/pull/337

**Comment by kordano** [comment]
Fixed with #458
