### ISSUE TITLE
[Bug]: or-join variables not respected

### ISSUE THREAD

**Issue by zoren** [replikativ/datahike#453]
### What version of Datahike are you using?

0.4.0

### What version of Java are you using?

11.0.11

### What operating system are you using?

macOS

### What database EDN configuration are you using?

no config, using vector of facts as input

### Describe the bug

It seems the join variables are not treated correctly. With datascript and Datomic I get the expected result.

### What is the expected behaviour?

That only `or-join` variables are considered input in the join. I expected `#{}` but got `#{[2] [1]}`.

### How can the behaviour be reproduced?

``` clojure
(q
 '[:in $ ?c
   :where
   (or-join [?e] ; don't join with the input var
            [?e :country ?c]
            [?e :country-iso ?c])
   :find ?e]
 [[1 :country :dk]
  [2 :country-iso :dk]]
 :se)
```

**Comment by kordano** [comment]
Thanks, I think this has something to do with #448, will add this bug to our tasks for next week.

**Comment by kordano** [comment]
This is working now with the latest release.

**Comment by zoren** [comment]
> This is working now with the latest release.

I still get `#{}` with release 0.5.1512.
