### ISSUE TITLE
[Bug]: konserve versions between release and testing are different

### ISSUE THREAD

**Issue by kordano** [replikativ/datahike#467]
### What version of Datahike are you using?

0.4.1480

### What version of Java are you using?

openjdk version "11.0.13" 2021-10-19

### What operating system are you using?

Ubuntu 20.04.3 LTS

### What database EDN configuration are you using?

Any

### Describe the bug

The used konserve version differs between different builds.

### What is the expected behaviour?

Testing should have the some konserve, hitchhiker-tree and clojure dependencies as the release build.

### How can the behaviour be reproduced?

Run a repl with `dev`and `test` build, check Datahike versions with `:meta` in the database record. Then see the difference:
`dev` is using konserve `0.5.3`while `test` is using `0.6.0alpha-3`.

**Comment by yflim** [comment]
I reproduced the issue and got konserve `0.5.1` with `dev` and `0.6.0alpha-1` with `test`.

Dependency trees from `clj [-A:<test|dev>] -Stree` (and, for good measure, dependency traces from `clj [-A:<test|dev>] -Strace`) point to the following paths for konserve:

In all builds: `io.replikativ/hitchhiker-tree 0.1.11` -> `io.replikativ/konserve 0.5.1`

However, that is superseded in `test` by:
`io.replikativ/datahike-jdbc 0.1.2-SNAPSHOT` -> `alekcz/konserve-jdbc 0.1.0-SNAPSHOT` -> `io.replikativ/konserve 0.6.0-alpha1`

(The version numbers `0.5.1` and `0.6.0alpha-1` are corroborated by [hitchhiker-tree/deps.edn](https://github.com/replikativ/hitchhiker-tree/blob/master/deps.edn) and [konserve-jdbc/project.clj](https://github.com/alekcz/konserve-jdbc/blob/master/project.clj), so it looks like there's a typo in the instructions.)

Might be worth writing something to check for other such inconsistencies?

**Comment by kordano** [comment]
Yes, it would be helpful to search for more inconsistencies.
AdditionalIy we could use a specific version for konserve instead of indirect dependency through the hitchhiker-tree. Also it would be a good idea to move the integration tests in the relevant backend-project. So we would only test for the file-  and in-memory backend inside Datahike. 
Could you prepare a PR for that @yflim?

**Comment by yflim** [comment]
For the record, the following are other current dependency inconsistencies between builds:
{com.cognitect/transit-java
 {:test #:mvn{:version "1.0.343"},
  :dev #:mvn{:version "0.8.332"},
  :release #:mvn{:version "0.8.332"}},
 commons-codec/commons-codec
 {:test #:mvn{:version "1.13"},
  :dev #:mvn{:version "1.15"},
  :release #:mvn{:version "1.13"}},
 org.clojure/tools.namespace
 {:test #:mvn{:version "1.1.0"}, :dev #:mvn{:version "1.2.0"}},
 com.cognitect/transit-clj
 {:test #:mvn{:version "1.0.324"},
  :dev #:mvn{:version "0.8.309"},
  :release #:mvn{:version "0.8.309"}}}
