### ISSUE TITLE
[Bug]: shadow-cljs dependency conflict 

### ISSUE THREAD

**Issue by awb99** [replikativ/datahike#474]
### What version of Datahike are you using?

Latest 

### What version of Java are you using?

16

### What operating system are you using?

Linux, guix

### What database EDN configuration are you using?

File backend

### Describe the bug

All the database stuff of datahike works. 

My usecase is to use datahike as a server side database in a reagent app with clojurescript compiled via shadow-cljs.

As soon as I add shadow - cljs to the dependencies there are lots of exceptions. 

The frontend witj shadow - cljs on its own works. 
The datahike backend on its own works. 
But shadow-cljs plus datahike does not work. 

I did 'clj - X:deps tree' to find out which dependency fucks it up.  But since both shadow-cljs and datahike bring in a lot of transitive dependencies I am not yet able to confirm which dependency is causing the hickup.

I will do some more research and do a follow up post.

### What is the expected behaviour?

Since I use tools.deps I did expect that tools.deps takes the highest version number of any dependencies needed, and this typically should work. In leiningen the version tsken depends on the order they appear in project.clj, which can lead to bad decisions. 

### How can the behaviour be reproduced?

I will post more once I have a better understanding of the dependencies that are conflicting in version number.

**Comment by awb99** [comment]
I have updated to the latest shadow-cljs version, and now shadow-cljs brings the most recent versions
of the clojurescript toolset:
```
org.clojure/clojurescript 
com.google.javascript/closure-compiler-unshaded
org.clojure/google-closure-library 
org.clojure/google-closure-library-third-party 
```
When the javascript that was used by datahike was used it brought lots of errors. 
Perhaps an incompatible upgrade in clojurescript or google clojure library.
Anyhow. Got it to work :-)

**Comment by kordano** [comment]
Great!
