### ISSUE TITLE
[Bug]: github release does not match clojars release version

### ISSUE THREAD

**Issue by kordano** [replikativ/datahike#562]
### What version of Datahike are you using?

0.5.1515

### What version of Java are you using?

irrelevant

### What operating system are you using?

irrelevant

### What database EDN configuration are you using?

irrelevant

### Describe the bug

The version `0.5.1515` on clojars does not match the release version on github `0.5.1506`.

### What is the expected behaviour?

should be the same

### How can the behaviour be reproduced?

each release with more than 1 commit, increases the version by one instead of the commits

**Comment by TimoKramer** [comment]
As I mentioned yesterday, the release did not work the last few months. There was no release on gh since 1506, so it clearly doesn't match 1515. There is a release now for 1516.
I am now using my own personal access token because I couldn't find the one we last used. will change that again.

**Comment by TimoKramer** [comment]
Please take a look if this issue can be closed.

**Comment by TimoKramer** [comment]
can this be closed now?
