### ISSUE TITLE
Integrate HTTP server

### ISSUE THREAD

**Issue by whilo** [replikativ/datahike#635]
### Describe the feature you would like to request

Integrate datahike-server in a mono repo style and provide a transparent clj client for datahike.api. 

### Describe the solution you would like

-

### Describe alternatives you've considered

-

**Comment by awb99** [comment]
The webserver should nit be in the default library. This will just add a whole bunch of depencies

**Comment by TimoKramer** [comment]
@awb99 no worries, @whilo is working on another solution

**Comment by whilo** [comment]
@awb99 At the moment we will add a dependency to https://github.com/babashka/http-client, is that a problem as well? I am thinking about removing it, but it will limit default datahike to not work distributed. Which maybe is fine.

**Comment by whilo** [comment]
Closed with #639.
