### ISSUE TITLE
add java api

### ISSUE THREAD

**Issue by grischoun** [replikativ/datahike#65]

**Comment by nickik** [comment]
Are talking here about a simple Java API to access the same function in a more idiomatic way or are we talking about a Java DSL like JOOQ for SQL (see: https://www.jooq.org/) or Datomic has something planned (See: https://github.com/stuarthalloway/presentations/blob/master/PhillyETE_2015/datalog.pdf).

I think both would be useful.

**Comment by grischoun** [comment]
In the next release, there will be an API that accesses the same functions in an idiomatic way.
But we are also planning to add a specific Java API for queries that should look like the Datomic proposal (even though no decision is final for now).

**Comment by whilo** [comment]
@nickik If you like to discuss the Java DSL further, please open a new issue. That would be appreciated :).
