### ISSUE TITLE
migrate namespace missing?

### ISSUE THREAD

**Issue by jdf-id-au** [replikativ/datahike#74]
I'm so excited about this project, thank you.

Where has the `datahike.migrate` namespace gone? Is there a new way to export and import?

`(require '[datahike.migrate :refer [export-db import-db]])` no longer works.

**Comment by kordano** [comment]
I kind of missed it in the datascript integration. I'll add it again with the new schema and time travel in the next patch release.

**Comment by kordano** [comment]
@jsmassa please add `datahike.migrate` namespace again with `export-db` and `import-db`. The datoms from the `:evt`index should be serialized as vectors and printed per line into an export file.

**Comment by whilo** [comment]
This is fixed now.
