### ISSUE TITLE
transact vs transact!

### ISSUE THREAD

**Issue by cjsauer** [replikativ/datahike#77]
Hi there 👋

Amazing project, thank you for sharing.

Out of curiosity, why `transact` instead of `transact!`? Both DataScript and Datomic use the bang `!` convention, I'm wondering why Datahike doesn't do the same.

**Comment by whilo** [comment]
`transact` is actually the one used by Datomic and our api namespace focuses on Datomic compatibility while we internally still use most of the DataScript conventions:

https://docs.datomic.com/on-prem/clojure/index.html#datomic.api/transact

The bang notation is unfortunately only losely used in Clojure land as far as I can tell. I think `transact!` corresponds to `transact-async` in Datomic @kordano.

**Comment by cjsauer** [comment]
🤦‍♂ oops, I misremembered, should've done a bit more research. Sorry for the noise here.
