### ISSUE TITLE
datahike api does not support lazy data structures

### ISSUE THREAD

**Issue by px0** [replikativ/datahike#78]
The Datahike API fails to support lazy sequences (`clojure.lang.LazySeq`). Seeing how pervasive lazy sequences are in Clojure, I would expect this to work, and to realize the sequences where required. I have observed this behaviour in both `q` and in `transact`.

For `q` it's as easy as adding this defmethod to `api.cljc`:

```clj
(defmethod d/q clojure.lang.LazySeq
  [query & inputs]
  (apply d/q (vec query) inputs))
```

I have not looked into what it would take to do something similar for `transact`.

**Comment by whilo** [comment]
Maybe I am missing your point, but `apply` is not lazy, so no matter what the semantics of `d/q` would be this would be eagerly evaluated in Clojure. Can you try to give a larger example without apply?

**Comment by whilo** [comment]
I assume this issue is resolved, open a new one if you need.
