### ISSUE TITLE
File-based storage medium fails in Winodws 10

### ISSUE THREAD

**Issue by orolle** [replikativ/datahike#8]
Hi,

I try to execute `(def conn (connect uri))` after calling `(create-database uri)` with `(def uri "datahike:file:///U:/path/to/my/database")` and get the exception below. It seems to create a database which cannot be read afterwords. My wild guess is that the parser mixes file path and class path seperators in Windows which is different from Unix-based systems, indicated by `Illegal char <:> at index 2` error description.

I use Windows 10, Oracle JDK 10.0.1+10, Clojure 1.9.0, datahike 0.1.2

The created database files: [database.zip](https://github.com/replikativ/datahike/files/2223598/database.zip)

The leveldb storage medium seems to work.

**Exception**
```
CompilerException clojure.lang.ExceptionInfo: Could not read key. {:type :read-error, :key :db, :exception #error {
 :cause "Illegal char <:> at index 2: /U:/path/to/my/database/data/0594e3b6-9635-5c99-8142-412accf3023b"
 :via
 [{:type java.nio.file.InvalidPathException
   :message "Illegal char <:> at index 2: /U:/path/to/my/database/data/0594e3b6-9635-5c99-8142-412accf3023b"
   :at [sun.nio.fs.WindowsPathParser normalize nil -1]}]
 :trace
 [[sun.nio.fs.WindowsPathParser normalize nil -1]
  [sun.nio.fs.WindowsPathParser parse nil -1]
  [sun.nio.fs.WindowsPathParser parse nil -1]
  [sun.nio.fs.WindowsPath parse nil -1]
  [sun.nio.fs.WindowsFileSystem getPath nil -1]
  [konserve.filestore$read_edn invokeStatic "filestore.clj" 169]
  [konserve.filestore$read_edn invoke "filestore.clj" 163]
  [konserve.filestore.FileSystemStore _get_in "filestore.clj" 341]
  [konserve.core$get_in$fn__15601$state_machine__8749__auto____15606$fn__15609 invoke "core.cljc" 71]
  [konserve.core$get_in$fn__15601$state_machine__8749__auto____15606 invoke "core.cljc" 68]
  [clojure.core.async.impl.ioc_macros$run_state_machine invokeStatic "ioc_macros.clj" 973]
  [clojure.core.async.impl.ioc_macros$run_state_machine invoke "ioc_macros.clj" 972]
  [clojure.core.async.impl.ioc_macros$run_state_machine_wrapped invokeStatic "ioc_macros.clj" 977]
  [clojure.core.async.impl.ioc_macros$run_state_machine_wrapped invoke "ioc_macros.clj" 975]
  [konserve.core$get_in$fn__15601 invoke "core.cljc" 68]
  [clojure.lang.AFn run "AFn.java" 22]
  [java.util.concurrent.ThreadPoolExecutor runWorker nil -1]
  [java.util.concurrent.ThreadPoolExecutor$Worker run nil -1]
  [java.lang.Thread run nil -1]]}}, compiling:(form-init9469297056318643012.clj:12:11) 
```

**Comment by whilo** [comment]
Yes, we are using a regex atm. which is not compatible with this drive based addressing: https://github.com/replikativ/datahike/blob/master/src/datahike/api.cljc#L19 We probably need to use some URI wrapper of Java.

**Comment by kordano** [comment]
Currently testing the path issues on Windows 10. Had some issues preparing the dev environment with leiningen over the last days but now it's running. There are still some errors coming from the path. I'll debug and try to fix that in the next days.

**Comment by joelkuiper** [comment]
I'm currently evaluating some persistence layers for a cross platform desktop app, and I'm really liking what I'm seeing here! Seems like such a great fit with cljfx. Was just curious if the Windows compatibility was still work in progress :blush: I could also give it a looksy if needed!

**Comment by whilo** [comment]
Hey @joelkuiper, happy new year! I am happy that you like what we do :). Having an example interaction with cljfx would be very cool, we have thought about that in the past as well, but have not had the time yet to do it. Lending a help with Windows support would also be very much appreciated as @kordano is currently involved with other Datahike features. Feel free to open issues and PRs and also join us on our discord channel https://discord.gg/kEBzMvb. I think the konserve file store should work on Windows, this is what I would check first. The storage configuration has changed in the meantime to hash maps and should probably be working by now.

**Comment by ronnac** [comment]
I have the same issue. I'd like windows support for konserve, too.

**Comment by joelkuiper** [comment]
Just checking in! Hey @whilo thank you, I just briefly tried it under Windows using the map configuration (instead of the JDBC-like string) and it appears to be working flawlessly when using the :file-based storage! I managed to integrate it into my cljfx app (still very much a work in progress prototype) by modifying this example https://github.com/cljfx/cljfx/blob/master/examples/e32_editable_table_cell_with_datascript.clj slightly to deference in the correct places, so far no issues! Thank you for the invite to discord, I'll be joining soon-ish :smile:

**Comment by whilo** [comment]
@joelkuiper That is great! :smile:  Please share the code with us on discord if you decide to make it openly accessible. 

Ok, if this is working for everyone else then we can close this issue, since the old URL configuration is supposed to be deprecated now anyway.
