### ISSUE TITLE
Fix cljdoc build

### ISSUE THREAD

**Issue by plexus** [replikativ/datahike#88]
Seems cljdoc is having a hard time analyzing the source code, see for instance this [build log](https://circleci.com/gh/cljdoc/builder/10602)

```
Execution error (ExceptionInfo) at cljs.analyzer/error (analyzer.cljc:751).
No such namespace: datahike.datom.Datom, could not locate datahike/datom/Datom.cljs, datahike/datom/Datom.cljc, or JavaScript source providing "datahike.datom.Datom" in file file:/tmp/cljdoc-io.replikativ-datahike-0.2.02686941967650676366/downloaded.jar!/datahike/schema.cljc
```

In the schema namespace the `Datom` class is being imported, but not the `datom` namespace. This fails unless the datom namespace has been loaded previously, since the class only comes into existence when the `deftype` is executed.

``` clojure
(ns datahike.schema
  (:require [clojure.spec.alpha :as s])
  (:import [datahike.datom Datom]))
```

`Datom` is only referenced in one place in `datahike.schema`, to [provide a type annotation](https://github.com/replikativ/datahike/blob/master/src/datahike/schema.cljc#L102).

``` clojure
(defn instant? [^Datom datom schema] ,,,)
```

I think there are two ways to fix is, either remove the import and change the type annotation to a fully qualified `^datahike.datom.Datom`, or add a `(:require [datahike.datom])` to the `ns` form.

**Comment by kordano** [comment]
Thanks for the suggestion. I'll fix the import.

**Comment by TimoKramer** [comment]
currently there is a fix to avoid the cljs-build of Datahike in cljdoc. So now the cljdoc build is fine but as soon as cljs is working again in datahike we will have to enable the cljs-build in cljdoc again.
