### ISSUE TITLE
Error when accessing uuid attribute with entity api on postgres backend

### ISSUE THREAD

**Issue by dinnymate** [replikativ/datahike#90]
**It does not happen on mem backend.**

```(def uri "datahike:pg://user:password@host:port/db")
(def conn (d/connect uri))

(d/transact conn [{:db/ident :uuid
                             :db/valueType :db.type/uuid
                             :db/cardinality :db.cardinality/one
                             :db/unique :db.unique/identity}])

(def uuid (java.util.UUID/randomUUID))

(d/transact conn [{:uuid uuid}])

(def e (d/entity @conn [:uuid uuid]))
(:uuid e) ;; => throws```

**Comment by whilo** [comment]
This issue is already resolved in the current development branch. Thank you for reporting though.

**Comment by dinnymate** [comment]
Which commit is this? I'm trying 1ae7bdcd05b1939c8684910e4adde54a861043dc but i'm not even able to connect to postgres.

**Comment by whilo** [comment]
Yes. We will move all backends except for memory and filesystem into separate dependencies. You need to include `[org.clojars.mihaelkonjevic/konserve-pg "0.1.2"]` in your own project dependencies to use the Postgres backend until we have completed this process.

**Comment by jsmassa** [comment]
The postgres backend is deprecated by now. The use of jdbc is encouraged instead
