### ISSUE TITLE
Unknown predicate 'get

### ISSUE THREAD

**Issue by Hendekagon** [replikativ/datahike#95]
I don't know if this is something Datahike doesn't support or if I'm doing it wrong, but have a clause in my query `[(get ?my-set ?k)]` which ensures that `?k` is in `?my-set`, a Clojure set:

`Execution error (ExceptionInfo) at datahike.query/filter-by-pred (query.cljc:548).
Unknown predicate 'get in [(get ?my-set ?k)]`

**Comment by whilo** [comment]
Datahike, like Datomic, is normalized, so logic variables do not normally bind collections, but primitive values like string, numbers or keywords. I am not sure how you intend to construct `?my-set`. You could use `clojure.core/get` explicitly to call it on the value of both logic variables, but this requires that they are bound and is not optimized in the same way as joining against the primitive values in the database themselves. Does that make sense? Feel free to post a longer example if it is still unclear.

**Comment by Hendekagon** [comment]
hi, I pass `?my-set` into the query like `{:in [% ?my-set] ...}` - the clause `[(get ?my-set ?k)]` ensures that `?k` is a member of `?my-set`
Well, using `clojure.core/get` works! Thank you for you help @whilo

**Comment by whilo** [comment]
You can add your primitives to https://github.com/replikativ/datahike/blob/master/src/datahike/query.cljc#L227. The scope of the Datalog query is not the same as the namespace you define it in because of quoting, therefore you have to use fully qualified names otherwise.

**Comment by whilo** [comment]
I will close that for now, feel free to open new issues, if you encounter issues.

**Comment by Hendekagon** [comment]
thank you @whilo
