### ISSUE TITLE
Support multiple named database roots (branches) per store

### ISSUE THREAD

**Issue by whilo** [replikativ/datahike#97]
I think it would be meaningful to allow a git branching like mechanism to fork the identity of the database into multiple named branches. Right now the root is always stored in konserve under the `:db` key, but this could be an arbitrarily named `:branch-name` and we provide a forking function. We should also keep track of all the branches that have been created, e.g. in a separate file that is updated whenever `fork` is invoked.

**Comment by kordano** [comment]
Sounds like a good idea. Since I'm re-structuring the db record with cleaner configuration we could add this information into the db as well.

**Comment by kordano** [comment]
We are moving these ideas to our roadmap plans, so I'm closing this issue here.
